### ISSUE TITLE
[Question]: Should #990 be tracked upstream

### ISSUE THREAD

**Issue by molangning** [danielmiessler/SecLists#1006]
If the automatic wordlist updater feature gets merged, the pull request will get overwritten. I feel that it should be tracked so that we can know if it will get added.

https://github.com/wallarm/jwt-secrets/pull/21

**Comment by Bilao600** [comment]
OK no worries, it works


Le lun. 8 avr. 2024 à 05:16, Mo Langning ***@***.***> a
écrit :

**Comment by molangning** [comment]
It has been merged upstream
