### ISSUE TITLE
payloads combined in windows not able to use .

### ISSUE THREAD

**Issue by c0ldb00t3r** [danielmiessler/SecLists#101]
Even i tried github cloning ,payloads merged with each others .any tips for using fuzzlist on windows.

![payload in windows](https://cloud.githubusercontent.com/assets/10518727/20867792/530ec4c4-ba72-11e6-90b6-567283c253cc.jpg)

**Comment by Eh2406** [comment]
Try opening in a different editor. Notepad only recognises windows line endings. It looks like the field have linux line endings.

**Comment by g0tmi1k** [comment]
Try notepad++ (https://notepad-plus-plus.org/
Or sublime text (https://www.sublimetext.com/)
...or atom (https://atom.io/)
