### ISSUE TITLE
Rahayu

### ISSUE THREAD

**Issue by 003567181064** [danielmiessler/SecLists#1022]
https://github.com/danielmiessler/SecLists/blame/0a0577d706345e3126c435338e0ca12e63ab7d62/Passwords/Pwdb-Public/Wordlists/ignis-10K.txt#L6487Dana
#1017

**Comment by g0tmi1k** [comment]
Hi @003567181064 

Not sure what this is for/suggesting so Im closing.

Please do reopen with more info
