### ISSUE TITLE
[Question]: Change github actions commit email

### ISSUE THREAD

**Issue by molangning** [danielmiessler/SecLists#1023]
The current email that seclists uses is `example@github.com`, which belongs to `throwaway-people` according to github. This account is user owned as seen in this [issue](https://github.com/nodejs/node/issues/1893) opened by that user. Should the email address be changed as it is not a bot/system account and if so, to what?

**Comment by ItsIgnacioPortal** [comment]
Nice catch! I've added a commit to #1015 which fixes this, replacing `example@github.com` with the email address of the official github-actions bot: https://github.com/orgs/community/discussions/26560

**Comment by molangning** [comment]
Good job for catching it!

**Comment by g0tmi1k** [comment]
Good idea.

I do believe this is now addressed :)
