### ISSUE TITLE
> .dmp and .sav

### ISSUE THREAD

**Issue by yash22586** [danielmiessler/SecLists#1024]
> .dmp and .sav
> 
> 
> .dmp is sometimes generated by windows unattended upgrade/migration scripts/tools
> 
> .sav commom for doze nimdas to name their +1 old backup of registry hives
> 
> .sys while you're at it.. pagefile(s)
> .out

> .sys in {value} :
> pycode: 
> sms.blinder;

_Originally posted by @yash22586 in https://github.com/Bo0oM/fuzz.txt/issues/43#issuecomment-2106148696_

GA6YTIHWTWXJ4ECFNPY7CPFNWAHRMQYBALQS55UCPUJIPULYBIJ6IN5D

**Comment by ItsIgnacioPortal** [comment]
`.sav` and `.dmp` are already in [Fuzzing/extension-test.txt](https://github.com/danielmiessler/SecLists/blob/0dac55d3f59718baeeb49b657414718bd210daf1/Fuzzing/extension-test.txt#L2356)

**Comment by g0tmi1k** [comment]
Thanks for the suggestion @yash22586 
As @ItsIgnacioPortal said, I think this is covered :)
