### ISSUE TITLE
[Feature request]: Import Fuzzing/XSS-Fuzzing into Fuzzing/XSS

### ISSUE THREAD

**Issue by molangning** [danielmiessler/SecLists#1033]

**Comment by g0tmi1k** [comment]
When you say import, are you talking about having the same stuff duplicated?

**Comment by molangning** [comment]
> When you say import, are you talking about having the same stuff duplicated?

Not really. In that directory there is both human and robot friendly version, so by moving and sorting the files it will be more easier to use.
