### ISSUE TITLE
[Question]: 

### ISSUE THREAD

**Issue by Damiean1204** [danielmiessler/SecLists#1103]
#Spring Campaign Review

Hi George,

We are ready to begin the review for the spring campaign. Here are a few tasks we need to do to prepare for the next one:

-[ ] Remove the "management" job title and replace it with tiered management titles.
-[ ] Remove the Contact column, as we regularly do not receive data on this.

**Comment by Damiean1204** [comment]
I would like to set some time aside to discuss how to expand our loan data.

**Comment by Damiean1204** [comment]
> I would like to set some time aside to discuss how to expand our loan data.

The spring review is complete

**Comment by Damiean1204** [comment]
The spring is complete

**Comment by g0tmi1k** [comment]
....Hu?
Closing & locking (I can't delete issues)
