### ISSUE TITLE
[Bug report]: RPC failed error while cloning SecLists repository

### ISSUE THREAD

**Issue by MethodWhite** [danielmiessler/SecLists#1119]
**Describe the bug**:

At the moment of cloning the repository a problem is generated in 92% of the repository because it cannot correctly verify the file(s).
**To reproduce**:

At the time of cloning at 92-93% (verification) in WSL2 Ubuntu 24.04.
**Expected behaviour**:

**Screenshots**:

[
![image](https://github.com/user-attachments/assets/a4e30a4c-5014-41e7-8679-e3389631d130)
]
**Additional context**:

**Next steps**:

- [ ] I intend to open a pull request later

error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8)
error: 5011 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

**Comment by ItsIgnacioPortal** [comment]
Seems like a network issue. Maybe check your internet connection?
/close
