### ISSUE TITLE
top million passwords minus one.

### ISSUE THREAD

**Issue by My1** [danielmiessler/SecLists#112]
the file 10_million_password_list_top_1000000.txt does have a million lines, but from a small look on it the 1 million-th line is empty.

**Comment by digininja** [comment]
You never come across an account with a blank password? :)

**Comment by My1** [comment]
@digininja any half-decent site makes sure that you cant get in without entering at least ANYTHING as a password.

there was only one instance I saw a blank password and that was a coding error while changing my hashing stuff, which kind of threw an empty password into bcrypt.

**Comment by miguemely** [comment]
Default router passwords? Some are blank.

**Comment by miguemely** [comment]
There is a lot of use for a blank password in a list.

Unsecured computers
Unsecured routers
Etc etc

**Comment by digininja** [comment]
Lots of embedded devices have it.

**Comment by miguemely** [comment]
Exactly.

Which is why a blank password is in this list. A lot more devices have a
blank password than you think.

**Comment by 0E800** [comment]
ALT255 ALT255 breaks the blank. You will need spaces atleast up to 10 to be
efficient as I believe it's possible to use spaced as a password.

**Comment by theJollySin** [comment]
By preference, if we believe the blank password is legit, it should be moved to the top / middle of the file, so that it is obvious that it is on purpose.  Being at the end of the file it just looks like a typo.

**Comment by its0x08** [comment]
I honestly thing that the last line is because some text editors in linux add a blank line by default and after saving the list and checking line numbers with any tool like `wc -l list.txt` for example it will show 1mln lines so thats why !

**Comment by theJollySin** [comment]
@its0x08 That is hilarious, and I think very probable.
