### ISSUE TITLE
Another possible word list

### ISSUE THREAD

**Issue by MikeDawg** [danielmiessler/SecLists#115]
Found the following word list while browsing today:  https://github.com/berzerk0/Probable-Wordlists

I'm wondering if this list (even though the licensing is currently "unknown") would make a good addition to this list. (That is, if it has a compatible licensing requirement)

**Comment by MikeDawg** [comment]
So, to fix what I said previously, it appears that berzerk0 pulled his list from this one. Is there a way to get it back into the list formatted the way berzerk0 does?

**Comment by g0tmi1k** [comment]
I know @danielmiessler and @jhaddix are really wanting to clean up the folders/naming convention.
What suggestions do you have in mind?

I've thrown my 2 cents into the mix with #180 & #128.

**Comment by g0tmi1k** [comment]
#176 adds in the source

How does #180 handle the formatting @MikeDawg ?

**Comment by MikeDawg** [comment]
Looks good to me

**Comment by g0tmi1k** [comment]
If its good, no alterations needed? So can this be closed?

**Comment by g0tmi1k** [comment]
Not heard back. Closing.
Feel free to re-open
