### ISSUE TITLE
Missing merged file

### ISSUE THREAD

**Issue by sbts** [danielmiessler/SecLists#116]
[Passwords/README](https://github.com/danielmiessler/SecLists/blob/master/Passwords/README) states that a file `merged.txt.tar.gz` should exist.

That file doesn't seem to be in `/passwords`

**Comment by xrobin** [comment]
Looks like commit  https://github.com/danielmiessler/SecLists/commit/9b8e66e6421a579dadae38fe3550be3967973f3a.
Is there a way to include a script that would re-generate this file?

**Comment by xrobin** [comment]
Actually this is a duplicate of issue #70

**Comment by g0tmi1k** [comment]
Duplicate of #172

Fixed in #180
