### ISSUE TITLE
Paths of Web document root

### ISSUE THREAD

**Issue by ron190** [danielmiessler/SecLists#135]
Do you have a list of default paths for commons document root?
Example:
```
/var/www/sites/all
/var/www/html/default/
/home/www/
/var/www/public/
...
```

**Comment by g0tmi1k** [comment]
Ive just very quickly made something and added them... WIP!

**Comment by ron190** [comment]
Here are some of mine:
https://github.com/ron190/jsql-injection/blob/master/src/main/java/com/jsql/view/swing/resources/list/file.txt

**Comment by g0tmi1k** [comment]
Thanks @ron190 !
Just added your missing values into here: https://github.com/danielmiessler/SecLists/pull/183/commits/3f79d071ce66d68b037ff2b06cc38be0540e91ef#diff-c619d49fc9ed6839095333b72a1d8937
