### ISSUE TITLE
To add: 42.zip

### ISSUE THREAD

**Issue by vdun** [danielmiessler/SecLists#140]
> The file contains 16 zipped files, which again contains 16 zipped files, which again contains 16 zipped files, which again contains 16 zipped, which again contains 16 zipped files, which contain 1 file, with the size of 4.3GB.
> 
> So, if you extract all files, you will most likely run out of space :-)

http://www.unforgettable.dk/

**Comment by g0tmi1k** [comment]
Fixed in #180
