### ISSUE TITLE
Version 3.4.0.CR1

### ISSUE THREAD

**Issue by Melvin-ngc** [danielmiessler/SecLists#144]
Hi
Is there an estimated release date for version 3.4.0.CR1
We are currently waiting for the blacklist functionality within KEYCLOAK-5244.
Thank you

**Comment by g0tmi1k** [comment]
Sorry, I'm lost/confused.
What do you mean by "3.4.0.CR1" ?

**Comment by g0tmi1k** [comment]
Not heard back.
Closing.
Feel free to re-open if needed.
