### ISSUE TITLE
same help plz

### ISSUE THREAD

**Issue by mhhakik** [danielmiessler/SecLists#165]
hi 
how can open this file (phpbb-withcount.txt.icloud) !!!

**Comment by lambdacasserole** [comment]
Looks like that was committed by accident. Just go back in the version history to before this change was made and you can get it [here](https://github.com/danielmiessler/SecLists/blob/788cdb889c84aec5afd24845cf7202fe65fcab10/Passwords/phpbb-withcount.txt). Suggest closing this one @danielmiessler.

**Comment by g0tmi1k** [comment]
Removed in #180.

Duplicate of #166
