### ISSUE TITLE
iCloud metadata files committed

### ISSUE THREAD

**Issue by lambdacasserole** [danielmiessler/SecLists#166]
@danielmiessler @jhaddix Looks like a bunch of iCloud metadata files were committed in place of the actual files. I'm thinking this may have been accidental.

**Comment by Inozemtsev-Ivan** [comment]
I guess it was done _automatically_ by build-in macOS feature called "Optimized Storage". To solve the issue you can just disable it or save files outside of Documents. Please refer: https://support.apple.com/en-us/HT207236

**Comment by g0tmi1k** [comment]
Removed in #180
