### ISSUE TITLE
pls help me to open .10_million_password_list_top_1000000.txt.icloud

### ISSUE THREAD

**Issue by axkami** [danielmiessler/SecLists#167]
how to open or seen this file pls help me to open .10_million_password_list_top_1000000.txt.icloud
i can not  use all 7 days ago file uploded

**Comment by lambdacasserole** [comment]
See issue #166, in the meantime you can go back in the version history and get the file you need from an earlier point in time: 

https://github.com/danielmiessler/SecLists/blob/788cdb889c84aec5afd24845cf7202fe65fcab10/Passwords/10_million_password_list_top_1000000.txt)

**Comment by rhtmm** [comment]
CAN YOU SEND ME THE FILE I CAN CHECK FOR FOU.IPSW DECODER CAN BE USED .BUT LET ME CHECK FIRST

**Comment by g0tmi1k** [comment]
Removed in #180.

Source: https://github.com/danielmiessler/SecLists/blob/master/Passwords/CommonCreds/10-million-password-list-top-1000000.txt
