### ISSUE TITLE
License file

### ISSUE THREAD

**Issue by UShan89** [danielmiessler/SecLists#179]
Hi there,
https://www.owasp.org/index.php/Projects/OWASP_SecLists_Project

From here, is it safe to assume that this project is with CC-3.0 license? I ask because I intend on making modifications in my fork.

**Comment by g0tmi1k** [comment]
```
Licensing
This project is licensed under the MIT license.
```
Source: https://github.com/danielmiessler/SecLists/blob/master/README.md
