### ISSUE TITLE
two web content directories

### ISSUE THREAD

**Issue by digininja** [danielmiessler/SecLists#181]
Is it deliberate that there are two web content directories:?

SecLists/Discovery/Web-Content/

SecLists/Discovery/Web_Content/

There are a few similar files in them but no direct conflicts, I'd guess they should be merged.

**Comment by mazen160** [comment]
I thought about the same too. Upvoting for doing a change on this part :+1:

**Comment by g0tmi1k** [comment]
This should be fixed in #180

**Comment by digininja** [comment]
Thanks.
