### ISSUE TITLE
lists of books/schools/street names/etc

### ISSUE THREAD

**Issue by erose1337** [danielmiessler/SecLists#193]
I have a repository that has organized lists of schools (public, private, and colleges), street names, and book titles that might be a useful addition to this repository - I did not see such lists in your repository already.

I collected the information from publicly available sources for the purpose of targeting "security questions" when testing a web application. The repository contains both the scraped/organized data, as well as the raw sources of information that the data was scraped from. You would probably not need the raw sources of information.

There are also other categories: cities, dates, names, pet names, and zip codes, but I believe this repository has at least some of these categories covered already.

If you would like to include any of this information in your repository, please let me know how you would like it organized. You can examine the data [here](https://github.com/erose1337/penetration_testing/tree/master/data).

**Comment by g0tmi1k** [comment]
Its a great idea!
Would love to see it added in (somehow).
Think you could do a PR?

**Comment by erose1337** [comment]
Done, the relevant [pull request is here](https://github.com/danielmiessler/SecLists/pull/198)
