### ISSUE TITLE
[Include] Param-Miner wordlist

### ISSUE THREAD

**Issue by s7x** [danielmiessler/SecLists#215]
Hello!

I thought it would be a good idea to add the wordlists from "Param-Miner" Burpsuite's extension by @albinowax. It contains unkeyed inputs related to web parameters, headers and such. It's a really awesome and complete ressource for uncommon attacks such as Cache Poisoning, OOB and such.

[Param-Miner wordlists](https://github.com/PortSwigger/param-miner/tree/master/resources)

Maybe it would be a good idea to have those in a specific directory in Discovery/Web-Content/, Fuzzing/ or Miscellaneous/? We need to cleanup some stuff in the wordlists tho, cause strings sometimes contain %s or %h.

Cheers & thanks for your work.

**Comment by g0tmi1k** [comment]
Great suggestion @s7x. I agree.
Would you like to have a good at making a PR? Else I can when I find some free time.

**Comment by s7x** [comment]
Hi @g0tmi1k, sure I can try, I never did this before but I guess we all have to start somewhere.
I'll see how it works and do it after understanding.

Cheers!

**Comment by albinowax** [comment]
I'd recommend combining the 'headers' and 'boring_headers' wordlists, and ignoring the others (as I think they're already in seclists in some form).

**Comment by g0tmi1k** [comment]
Merge'd: https://github.com/danielmiessler/SecLists/commit/f8987930efe2a60ee95a76eb9233ad6a07bc6349
