### ISSUE TITLE
Feature Request API wordlists

### ISSUE THREAD

**Issue by 0xtavian** [danielmiessler/SecLists#217]
I find myself prodding unknown APIs more and more. It would be great to have a wordlist similar to https://github.com/chrislockard/api_wordlist incorporated.

**Comment by g0tmi1k** [comment]
Good suggestion @0xtavian! I have to agree.
Would you like to have a good at making a PR? Else I can when I find some free time.

**Comment by g0tmi1k** [comment]
Thanks for the suggest!
