### ISSUE TITLE
File name too long: b'/usr/share/dict/seclists/Payloads/File-Names/max-length

### ISSUE THREAD

**Issue by blshkv** [danielmiessler/SecLists#226]
```
!!! copy /var/tmp/portage/app-dicts/seclists-2018.3/image/usr/share/dict/seclists/Payloads/File-Names/max-length/Aa0Aa1Aa2Aa3Aa4Aa5Aa6Aa7Aa8Aa9Ab0Ab1Ab2Ab3Ab4Ab5Ab6Ab7Ab8Ab9Ac0Ac1Ac2Ac3Ac4Ac5Ac6Ac7Ac8Ac9Ad0Ad1Ad2Ad3Ad4Ad5Ad6Ad7Ad8Ad9Ae0Ae1Ae2Ae3Ae4Ae5Ae6Ae7Ae8Ae9Af0Af1Af2Af3Af4Af5Af6Af7Af8Af9Ag0Ag1Ag2Ag3Ag4Ag5Ag6Ag7Ag8Ag9Ah0Ah1Ah2Ah3Ah4Ah5Ah6Ah7Ah8Ah9Ai0Ai1Ai2Ai3Ai4 -> /usr/share/dict/seclists/Payloads/File-Names/max-length/Aa0Aa1Aa2Aa3Aa4Aa5Aa6Aa7Aa8Aa9Ab0Ab1Ab2Ab3Ab4Ab5Ab6Ab7Ab8Ab9Ac0Ac1Ac2Ac3Ac4Ac5Ac6Ac7Ac8Ac9Ad0Ad1Ad2Ad3Ad4Ad5Ad6Ad7Ad8Ad9Ae0Ae1Ae2Ae3Ae4Ae5Ae6Ae7Ae8Ae9Af0Af1Af2Af3Af4Af5Af6Af7Af8Af9Ag0Ag1Ag2Ag3Ag4Ag5Ag6Ag7Ag8Ag9Ah0Ah1Ah2Ah3Ah4Ah5Ah6Ah7Ah8Ah9Ai0Ai1Ai2Ai3Ai4 failed.
```

I'm unable to copy that file from tmpfs to ext4. Any ideas?

**Comment by blshkv** [comment]
This is what I did on Pentoo too:
https://github.com/pentoo/pentoo-overlay/blob/master/app-dicts/seclists/seclists-2018.3.ebuild#L19

but the question: what is the point of having this file if it is impossible to use it? How a penetration tester could still use it?

**Comment by drwetter** [comment]
Seems to me 256 bytes long which exceeds the limits of most Linux fs: https://en.wikipedia.org/wiki/Comparison_of_file_systems#Limits. Just cutting it by one char should help

**Comment by Natfan** [comment]
Could this not be shortened to a regex pattern?
`(A[a-i][0-9]){85}` seems to work?
https://regexr.com/44oth for a live demonstration.

**Comment by g0tmi1k** [comment]
Fixed up!
