### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by kirtiso** [danielmiessler/SecLists#233]
Hello sir,

Can u tell me what is command for running in kali linux???

**Comment by g0tmi1k** [comment]
either `apt-get install seclists` (more info: https://tools.kali.org/password-attacks/seclists)
or `git clone https://github.com/danielmiessler/SecLists.git`
or `wget https://github.com/danielmiessler/SecLists/archive/master.zip; unzip master.zip; rm -f master.zip`
