### ISSUE TITLE
List Addition - A list of secret related keywords should be added

### ISSUE THREAD

**Issue by nsonaniya2010** [danielmiessler/SecLists#245]
Here is the example of list which should be added:

```
secret
secret_key
token
secret_token
auth_token
access_token
username
password
pass
aws_access_key_id
aws_secret_access_key
secretkey
authtoken
authkey
client_secret
encryption-key
encryptionkey
secretkey
secret-key
api_key
api_secret_key
api
private_key
authorization
Bearer
authorization_token
``` 
and more.

**Comment by g0tmi1k** [comment]
Feel free to open a pull request!

Whats the source of the above list?

**Comment by nsonaniya2010** [comment]
there is no source but these are the keywords generally used to search for credentials on github and other source.

**Comment by g0tmi1k** [comment]
Fair enough :).
I can either, wait for your PR and merge it in, else using what you put above, I can make a PR and merge that in.

**Comment by nsonaniya2010** [comment]
Done.

**Comment by g0tmi1k** [comment]
Cheers for the PR 👍
