### ISSUE TITLE
websphere.txt update

### ISSUE THREAD

**Issue by Hamid-K** [danielmiessler/SecLists#255]
The following default/common endpoints are missing from the list in websphere.txt:

/wps/wsrp/WSRPBaseService_v2
/wps/wsrp/WSRPBaseService_v2/*
/wps/wsrp/WSRPPortletManagementService
/wps/wsrp/WSRPPortletManagementService/*
/wps/wsrp/WSRPPortletManagementService_v2
/wps/wsrp/WSRPPortletManagementService_v2/*
/wps/wsrp/WSRPServiceDescriptionService
/wps/wsrp/WSRPServiceDescriptionService/*
/wps/wsrp/WSRPServiceDescriptionService_v2
/wps/wsrp/WSRPServiceDescriptionService_v2/*
/wps/wsrp/WsrpProxyPortlet

/mycontenthandler/wcmrest/Project
/mycontenthandler/wcmrest/
/mycontenthandler/
/wcmrest/

**Comment by g0tmi1k** [comment]
feel free to open up a PR

**Comment by g0tmi1k** [comment]
Merged!
Thank you
