### ISSUE TITLE
Trojan found in the folders

### ISSUE THREAD

**Issue by mrkhew** [danielmiessler/SecLists#257]
![trojan](https://user-images.githubusercontent.com/31813140/50227963-ed94fd00-03e1-11e9-8eb6-38ecf2cb6954.jpg)
![trojan2](https://user-images.githubusercontent.com/31813140/50227983-f259b100-03e1-11e9-8182-04d0021e8572.png)

Is this normal?

**Comment by g0tmi1k** [comment]
Yup

**Comment by mrkhew** [comment]
Ok thanks
