### ISSUE TITLE
Question about latest commit

### ISSUE THREAD

**Issue by toxydose** [danielmiessler/SecLists#259]
Hi,

I found that in https://github.com/danielmiessler/SecLists/commit/778b16115f846a1fb76729156bf8aa8380848fef were deleted some big and important files. Are they duplicates, or in what reason the files were deleted? There is no info about it in commit.

Thanks
Alex

**Comment by g0tmi1k** [comment]
Hey @toxydose 
Looks like something went wrong - I will shortly recover it.
