### ISSUE TITLE
Duplicate (mixed case) file in Fuzzing Directory

### ISSUE THREAD

**Issue by ChrisMcKee** [danielmiessler/SecLists#284]
```
'Fuzzing/UserAgents-IE.txt'
'Fuzzing/useragents-ie.txt'
```
One needs blowing away.

**Comment by g0tmi1k** [comment]
@ChrisMcKee I'm not seeing this.
Are you using the latest version?

https://github.com/danielmiessler/SecLists/tree/master/Fuzzing

```
$ ls -1 Fuzzing | grep -i user
UserAgents-ie.txt
UserAgents.fuzz.txt
user-agents
$
```

**Comment by ChrisMcKee** [comment]
![image](https://user-images.githubusercontent.com/83597/55477357-bc4ae080-5610-11e9-87b3-d3ea6865ec7c.png)

**Comment by g0tmi1k** [comment]
@ChrisMcKee
Your screenshot has different filenames to whats in the top/first comment.

**Comment by g0tmi1k** [comment]
Their contents is different too.
This isn't a duplicate file.
```
$ wc -l Fuzzing/UserAgents*                                                                                                                                   (upstream-master)
   245 Fuzzing/UserAgents-ie.txt
  2454 Fuzzing/UserAgents.fuzz.txt
  2699 total
$
```

**Comment by ChrisMcKee** [comment]
@g0tmi1k you closed it but there are still two files with the same name and different casing. 
.fuzz was only highlighted because i typed userage in the browsers find control; I wasn't saying it was the same thing.

![image](https://user-images.githubusercontent.com/83597/55640636-f7414580-57c3-11e9-80c9-dbb3ba7798f1.png)

That better^ 

The content may not be identical but the file naming is; which is what the issue was for.

**Comment by 0x6773** [comment]
I can confirm, there are two duplicate files inside `Fuzzing` 

```shell
~/SecLists/Fuzzing master $ git rev-parse HEAD
aca3a1bb5cb8fe52bffb0cfe5aed260cf3aa0870 # master
~/SecLists/Fuzzing master $ wc * | grep -i user                                                                                                                                                                                           
wc: Polyglots: Is a directory
wc: user-agents: Is a directory
       0        0        0 user-agents
    2454     8756   110375 UserAgents.fuzz.txt
     245     2752    20678 useragents-ie.txt # this 
     245     2752    20678 UserAgents-IE.txt # and this
~/SecLists/Fuzzing master $ diff useragents-ie.txt UserAgents-IE.txt
 # no diff
~/SecLists/Fuzzing master $
```

**Comment by g0tmi1k** [comment]
```
```
[seclists]$ git rev-parse HEAD
aca3a1bb5cb8fe52bffb0cfe5aed260cf3aa0870
[seclists]$
[seclists]$ cd Fuzzing/
[Fuzzing]$
[Fuzzing]$ wc * | grep -i user
wc: Polyglots: Is a directory
     245     2752    20678 UserAgents-ie.txt
    2454     8756   110375 UserAgents.fuzz.txt
wc: user-agents: Is a directory
       0        0        0 user-agents
[Fuzzing]$ 
```

However...

```
[tmp]$ curl -I https://raw.githubusercontent.com/danielmiessler/SecLists/master/Fuzzing/useragents-ie.txt
HTTP/1.1 200 OK
...SNIP...
Content-Length: 20678
...SNIP...
Expires: Tue, 09 Apr 2019 22:12:19 GMT
Source-Age: 20

[tmp]$
[tmp]$ curl -I https://raw.githubusercontent.com/danielmiessler/SecLists/master/Fuzzing/UserAgents-IE.txt
HTTP/1.1 200 OK
...SNIP...
Content-Length: 20678
...SNIP...
Expires: Tue, 09 Apr 2019 22:12:22 GMT
Source-Age: 44

[tmp]$
```

So I've got a mistake locally.
Sorry @ChrisMcKee and thanks for the input @0x6773 .
I stand correct, I messed up =)

I'll dig into it tomorrow.

**Comment by g0tmi1k** [comment]
Well that was simple enough...

```
[Fuzzing]$ git config core.ignorecase                                                                                                                          
true
[Fuzzing]$
[Fuzzing]$ git config core.ignorecase false                                                                                                                    
[Fuzzing]$                                                                                                                                               
[Fuzzing]$ git status                                                                                                                                    
On branch upstream-master
Your branch is up to date with 'upstream/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	FormatString-Jhaddix.txt
	HTML5sec-Injections-Jhaddix.txt
	SSI-Injection-Jhaddix.txt
	URI-hex.txt
	Unicode.txt
	UserAgents-ie.txt
	XSS-Bypass-Strings-BruteLogic.txt
	XSS-With-Context-Jhaddix.txt
	command-injection-commix.txt
	db2enumeration.fuzzdb.txt

nothing added to commit but untracked files present (use "git add" to track)
[Fuzzing]$
```

**Comment by g0tmi1k** [comment]
```
pi@raspberrypi:~/SecLists $ find . -print0 | sort -z | uniq -diz
pi@raspberrypi:~/SecLists $
```

Should be good now!

Thanks and sorry once again @ChrisMcKee
