### ISSUE TITLE
Add graphql to a Web-Content database

### ISSUE THREAD

**Issue by tehmoon** [danielmiessler/SecLists#288]
Hi!

I recently came across a `/graphql` endpoint which was not in any `Discovery/Web-Content/` wordlists. I think it's a pretty default path for people that use GraphQL as it is pointed out here: https://graphql.org/learn/serving-over-http/ 

I use raft medium.txt but like everybody I'm assuming, I also built my own.

How possible would it be to add that endpoint somewhere? I don't really know how to proceed, where to put it in the file, but I figured it could help some people.

Happy to make a PR following some recommendations.

**Comment by g0tmi1k** [comment]
Thanks for the suggestion. Added to `big.txt`
