### ISSUE TITLE
Some raft files contain invalid characters (or wrong encoding used)

### ISSUE THREAD

**Issue by u0m3** [danielmiessler/SecLists#291]
Some lines like https://github.com/danielmiessler/SecLists/blob/master/Discovery/Web-Content/raft-large-directories.txt#L15513 trigger errors when loaded/loading in some tools (for example wfuzz).
Is it possible to check if in the process of compiling these lists, files with different encoding were not mixed?

**Comment by g0tmi1k** [comment]
This seams to clean it up:

```
$ iconv -f utf-8 -t utf-8 -c raft-large-directories.txt | sed '/^$/d' > tmp; mv tmp raft-large-directories.txt
```

**Comment by g0tmi1k** [comment]
Thanks for the suggestion!
