### ISSUE TITLE
This is gonna sound dumb

### ISSUE THREAD

**Issue by bozeyman9000** [danielmiessler/SecLists#308]
how the heck do i download this as a file, when i click download it opens a page with all the passwords, and i tried using git clone the address bar... like the official way to do this.

**Comment by bozeyman9000** [comment]
oh i found the answer... i was like further down the file path... but is there a way to grab certain files from git then?

**Comment by srasku** [comment]
If you click on "Raw" you can save the file from your browser.

**Comment by g0tmi1k** [comment]
Hi!

Either you can download the whole project, using either git or http (see the readme).
Else you can grab single files - by pressing 'raw' in the top right of the file menu.
