### ISSUE TITLE
Symfony CMS

### ISSUE THREAD

**Issue by janfry** [danielmiessler/SecLists#31]
It looks like there are a few Symfony entries in the raft files but it may be worth creating a separate entry under the CMS directory.

A few interesting files from verison 1.x (now EoL):
/frontend_dev.php
/frontend_staging.php
/admin
/backend_dev.php
/backend.php

From version 2.x
/app.php
/web/app.php
/app_dev.php
/web/app_dev.php
/config.php
/app_dev.php/admin
/admin

**Comment by danielmiessler** [comment]
Awesome! Can you create a list and submit it?
