### ISSUE TITLE
CMS fingerprinting

### ISSUE THREAD

**Issue by toxydose** [danielmiessler/SecLists#320]
Hi,
How about to create wordlist in Discovery/Web-Content/CMS with unique endpoints of most popular CMSs to fingerprint usage of them?
It should contain non-security-impact endpoints than usually should not be hidden - such as common static file paths, etc in the reason of most accurate fingerprinting.

**Comment by g0tmi1k** [comment]
If you have a source of this, would love to add it.

**Comment by molangning** [comment]
https://github.com/trickest/wordlists/tree/main/technologies

im adding this

**Comment by g0tmi1k** [comment]
Done (thanks to @molangning )
