### ISSUE TITLE
Twitter updated their bannedPassword list...

### ISSUE THREAD

**Issue by fat-tire** [danielmiessler/SecLists#34]
31 new passwords (though they introduced a duplicate, "letmein" for some reason)

To find the updated list, log out of twitter.com if you're signed in, then visit their [signup page](https://www.twitter.com/signup).  Find "bannedPasswords" in the page source.  You can probably guess how to extract it from there, and I won't deprive you of the fun in figuring it out.

Thanks to @binkybear for suggesting I forward this here.

**Comment by danielmiessler** [comment]
Added. Thanks so much guys!
