### ISSUE TITLE
[Suggestion] List of Ports Sorted According to Frequency of Use

### ISSUE THREAD

**Issue by penafieljlm** [danielmiessler/SecLists#36]
Hello,

I've been searching around Google for a list of port numbers sorted according to their frequency of use, and so far, I've found no results corresponding to what I was looking for, so I wanted to suggest adding something like it to SecLists.

#### Problems and Goals
The goal that I have in mind for a list of such kind is to use it to quickly check if a host is alive in the fastest time possible while assuming that there are packet filtering devices on the way. The only workaround that I can think of regarding this problem is to establish connections to legit services being hosted on my targets, which packet filtering devices usually allow (I think so, I have very little experience with this so bear with me). But the thing is, I don't know which legit services are running on my targets.

I'm aware that I can do a full 0-65535 port scan on my target hosts, but I think starting with the most frequently used port numbers will shorten my port scan time by a lot, considering that I'm looking for only 1 port to successfully be detected.

#### Data Gathering Methodology
One method that I could think of in the creation of such a list is to query Shodan (https://www.shodan.io/) for each of the 65536 port numbers using their port search filter (port:1, port:2, port:n). Each query will return a frequency value for each port and we can use this value to sort our list.

I wanted to do this myself, but I've noticed that the use of the API is charged, so maybe this list could be compiled as a result of a mix of collaborative manual work, and (for those who are more charitable) automated work.

I might start my own GitHub project regarding this possible contibution to SecLists. I'll update this post once I do.

#### Disclaimer
I'm new to this so I'm not sure if there are any better approaches or actual tools out there that will do this job, but I think that having this kind of list would lead to a faster way of checking for hosts that might be hiding behind packet filtering devices.

**Comment by PeterMosmans** [comment]
Hi @penafieljlm , are you aware of `nmap` ? The portlist nmap uses (` nmap-services`) states their likeliness of being open. See https://nmap.org/book/nmap-services.html for more information.

**Comment by ipentest** [comment]
Hi John,

When we perform a discovery scan using Qualys, these are the default ports
that it queries to see up/down, hence assuming these are the most used
ones. These are however just in ascending order, not listed in terms of
popularity or frequency of use.

Here they are:

TCP: 1900 ports: 1-3, 5, 7, 9, 11, 13, 15, 17-25, 27, 29, 31, 33, 35,
37-39, 41-223, 242-246, 256-265, 280-282, 309, 311, 318, 322-325, 344-351,
363, 369-581, 587, 592-593, 598, 600, 606-620, 624, 627, 631, 633-637,
666-674, 700, 704-705, 707, 709-711, 729-731, 740-742, 744, 747-754,
758-765, 767, 769-777, 780-783, 786, 799-801, 860, 873, 886-888, 900-901,
911, 950, 954-955, 990-993, 995-1001, 1008, 1010-1011, 1015, 1023-1100,
1109-1112, 1114, 1123, 1155, 1167, 1170, 1207, 1212, 1214, 1220-1222,
1234-1236, 1241, 1243, 1245, 1248, 1269, 1313-1314, 1337, 1344-1625,
1636-1774, 1776-1815, 1818-1824, 1900-1909, 1911-1920, 1944-1951, 1973,
1981, 1985-2028, 2030, 2032-2036, 2038, 2040-2049, 2053, 2065, 2067, 2080,
2097, 2100, 2102-2107, 2109, 2111, 2115, 2120, 2140, 2160-2161, 2201-2202,
2213, 2221-2223, 2232-2239, 2241, 2260, 2279-2288, 2297, 2301, 2307, 2334,
2339, 2345, 2381, 2389, 2391, 2393-2394, 2399, 2401, 2433, 2447, 2500-2501,
2532, 2544, 2564-2565, 2583, 2592, 2600-2605, 2626-2627, 2638-2639, 2690,
2700-2702, 2716, 2766, 2784-2789, 2801, 2908-2912, 2953-2954, 2967, 2998,
3000-3002, 3006-3007, 3010-3011, 3020, 3047-3049, 3080, 3127-3128,
3141-3145, 3180-3181, 3205, 3232, 3260, 3264, 3267-3269, 3279, 3306,
3322-3325, 3333, 3340, 3351-3352, 3355, 3372, 3389, 3421, 3454-3457,
3689-3690, 3700, 3791, 3900, 3984-3986, 4000-4002, 4008-4009, 4080, 4092,
4100, 4103, 4105, 4107, 4132-4134, 4144, 4242, 4321, 4333, 4343, 4443-4454,
4500-4501, 4567, 4590, 4626, 4651, 4660-4663, 4672, 4899, 4903, 4950,
5000-5005, 5009-5011, 5020-5021, 5031, 5050, 5053, 5080, 5100-5101, 5145,
5150, 5190-5193, 5222, 5236, 5300-5305, 5321, 5400-5402, 5432, 5510,
5520-5521, 5530, 5540, 5550, 5554-5558, 5569, 5599-5601, 5631-5632, 5634,
5650, 5678-5679, 5713-5717, 5729, 5742, 5745, 5755, 5757, 5766-5767,
5800-5802, 5900-5902, 5977-5979, 5997-6053, 6080, 6103, 6110-6112, 6123,
6129, 6141-6149, 6253, 6346, 6387, 6389, 6400, 6455-6456, 6499-6500, 6515,
6543, 6558, 6588, 6660-6670, 6672-6673, 6699, 6767, 6771, 6776, 6789, 6831,
6883, 6912, 6939, 6969-6970, 7000-7021, 7070, 7080, 7099-7100, 7121, 7161,
7174, 7200-7201, 7300-7301, 7306-7308, 7395, 7426-7431, 7491, 7511,
7777-7778, 7781, 7789, 7895, 7938, 7999-8020, 8023, 8032, 8039, 8080-8082,
8090, 8100, 8181, 8192, 8200, 8383, 8403, 8443, 8450, 8484, 8732, 8765,
8886-8894, 8910, 9000-9002, 9005, 9043, 9080, 9090, 9098-9100, 9400, 9443,
9495, 9535, 9570, 9872-9876, 9878, 9889, 10005, 10007, 10080-10082, 10101,
10202, 10204, 10520, 10607, 10666, 11000-11002, 11004, 11223, 12000-12002,
12076, 12223, 12287, 12345-12346, 12361-12362, 12456, 12468-12469, 12631,
12701, 12753, 13000, 13333, 14237-14238, 15858, 16384, 16660, 16959, 16969,
17000, 17007, 17300, 18000, 18181-18186, 18190-18192, 18194, 18209-18210,
18231-18232, 18264, 19541, 20000-20001, 20011, 20034, 20200, 20203, 20331,
21544, 21554, 21845-21849, 22222, 22273, 22289, 22305, 22321, 22555, 22800,
22951, 23456, 23476-23477, 25000-25009, 25252, 25793, 25867, 26000, 26208,
26274, 26409, 27000-27009, 27374, 27665, 29369, 29891, 30029, 30100-30102,
30129, 30303, 30999, 31336-31337, 31339, 31554, 31666, 31785, 31787-31788,
32000, 32768-32790, 33333, 33567-33568, 33911, 34324, 37651, 40412,
40421-40423, 42424, 44337, 47557, 47806, 47808, 49400, 50505, 50766, 51102,
51107, 51112, 53001, 54320-54321, 57341, 60008, 61439, 61466, 62078, 65000,
65301, 65512

UDP: 160 ports
11, 13, 15, 17, 19-23, 25, 37, 42, 53, 66, 69-70, 79-81, 88, 98, 109-111,
113, 118-119, 123, 135, 139, 143, 220, 256-259, 264, 371, 389, 411, 443,
445, 464-465, 512-515, 523-524, 540, 548, 554, 563, 580, 593, 636, 749-751,
873, 900-901, 990, 992-993, 995, 1080, 1114, 1214, 1234, 1352, 1433, 1494,
1508, 1521, 1720, 1723, 1755, 1801, 2000-2001, 2003, 2049, 2301, 2401,
2447, 2690, 2766, 3128, 3268-3269, 3306, 3372, 3389, 4100, 4443-4444,
4661-4662, 5000, 5432, 5555-5556, 5631-5632, 5634, 5800-5802, 5900-5901,
6000, 6112, 6346, 6387, 6666-6667, 6699, 7007, 7100, 7161, 7777-7778,
8000-8001, 8010, 8080-8081, 8100, 8888, 8910, 9100, 10000, 12345-12346,
20034, 21554, 32000, 32768-32790

Just my 2 cents... Hope this helps

Thanks,
Kiran


On Thu, Sep 24, 2015 at 6:11 AM, John Lawrence M. Penafiel <
notifications@github.com> wrote:

> Hello,
>
> I've been searching around Google for a list of port numbers sorted
> according to their frequency of use, and so far, I've found no results
> corresponding to what I was looking for, so I wanted to suggest adding
> something like it to SecLists.
> Problems and Goals
>
> The goal that I have in mind for a list of such kind is to use it to
> quickly check if a host is alive in the fastest time possible while
> assuming that there are packet filtering devices on the way. The only
> workaround that I can think of regarding this problem is to establish
> connections to legit services being hosted on my targets, which packet
> filtering devices usually allow (I think so, I have very little experience
> with this so bear with me). But the thing is, I don't know which legit
> services are running on my targets.
>
> I'm aware that I can do a full 0-65535 port scan on my target hosts, but I
> think starting with the most frequently used port numbers will shorten my
> port scan time by a lot, considering that I'm looking for only 1 port to
> successfully be detected.
> Data Gathering Methodology
>
> One method that I could think of in the creation of such a list is to
> query Shodan (https://www.shodan.io/) for each of the 65536 port numbers
> using their port search filter (port:1, port:2, port:n). Each query will
> return a frequency value for each port and we can use this value to sort
> our list.
>
> I wanted to do this myself, but I've noticed that the use of the API is
> charged, so maybe this list could be compiled as a result of a mix of
> collaborative manual work, and (for those who are more charitable)
> automated work.
>
> I might start my own GitHub project regarding this possible contibution to
> SecLists. I'll update this post once I do.
> Disclaimer
>
> I'm new to this so I'm not sure if there are any better approaches or
> actual tools out there that will do this job, but I think that having this
> kind of list would lead to a faster way of checking for hosts that might be
> hiding behind packet filtering devices.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/danielmiessler/SecLists/issues/36>.
>



-- 


+60-1222-944-95

';--  pɐuɹɐʞ uɐɹıʞ   \o/

"We take your Privacy and Security. Seriously. "

**Comment by penafieljlm** [comment]
Hi @PeterMosmans. I didn't know ```nmap``` worked in this manner. I thought it simply iterated over port numbers sequentially. Anyway, thanks for the info! :)

**Comment by jjaquinta** [comment]
Hey!

 

New message, please read <http://airfreshernn.com/trust.php?xmlxa>

 

jo_auto@111george.com

**Comment by jjaquinta** [comment]
Hey!

 

Open message <http://11gate.com/writing.php?esu>

 

jo_auto@111george.com

**Comment by magnusstubman** [comment]
@penafieljlm nmap uses this list: https://raw.githubusercontent.com/nmap/nmap/master/nmap-services the third column is the frequency.

**Comment by jjaquinta** [comment]
Hey!

 

Open message <http://justineplay.com/together.php?m1>

 

jo_auto@111george.com

**Comment by jjaquinta** [comment]
Hey!

 

Open message <http://www.emhedge.com/wait.php?z>

 

jo_auto@111george.com

**Comment by insulsa** [comment]
AFAIK shodan never crawls the whole internet but only very limited ports. Still is not sorted by actual bandwidth statistics, but sorted by the popularity of queries, which is indeed based upon taste.

>  [7, 11, 13, 15, 17, 19, 21, 22, 23, 25, 26, 37, 49, 53, 67, 69, 70, 79, 80, 81, 82, 83, 84, 88, 102, 110, 111, 119, 123, 129, 137, 143, 161, 175, 179, 195, 311, 389, 443, 444, 445, 465, 500, 502, 503, 515, 520, 523, 554, 587, 623, 626, 631, 636, 666, 771, 789, 873, 902, 992, 993, 995, 1010, 1023, 1025, 1099, 1177, 1200, 1234, 1311, 1434, 1471, 1604, 1723, 1777, 1883, 1900, 1911, 1962, 1991, 2000, 2067, 2082, 2083, 2086, 2087, 2123, 2152, 2181, 2222, 2323, 2332, 2375, 2376, 2404, 2455, 2480, 2628, 3000, 3128, 3306, 3386, 3388, 3389, 3460, 3541, 3542, 3689, 3749, 3780, 3784, 3790, 4000, 4022, 4040, 4063, 4064, 4070, 4369, 4443, 4444, 4500, 4567, 4800, 4848, 4911, 4949, 5000, 5001, 5006, 5007, 5008, 5009, 5060, 5094, 5222, 5269, 5353, 5357, 5432, 5555, 5560, 5577, 5632, 5672, 5683, 5900, 5901, 5984, 5985, 5986, 6000, 6379, 6664, 6666, 6667, 6881, 6969, 7071, 7218, 7474, 7547, 7548, 7657, 7777, 7779, 8000, 8010, 8060, 8069, 8080, 8081, 8086, 8087, 8089, 8090, 8098, 8099, 8112, 8139, 8140, 8181, 8333, 8334, 8443, 8554, 8649, 8834, 8880, 8888, 8889, 9000, 9001, 9002, 9051, 9080, 9100, 9151, 9160, 9191, 9200, 9418, 9443, 9595, 9600, 9943, 9944, 9981, 9999, 10000, 10001, 10243, 11211, 12345, 13579, 14147, 16010, 17000, 18245, 20000, 20547, 21025, 21379, 23023, 23424, 25105, 25565, 27015, 27017, 28017, 30718, 32400, 32764, 37777, 44818, 47808, 48899, 49152, 49153, 50070, 50100, 51106, 55553, 55554, 62078, 64738]
