### ISSUE TITLE
List of dangerous/risky JS functions on client-side

### ISSUE THREAD

**Issue by bkimminich** [danielmiessler/SecLists#367]
A list of dangerous functions offered by JS frameworks could be used by tools like OWASP ZAP or BurpSuite to check if any are used in the JS code delivered to the browser by a SPA. Here are some examples:

* From Angular 2+ using these can make XSS possible, see https://angular.io/guide/security:
  * `bypassSecurityTrustHtml`
  * `bypassSecurityTrustScript`
  * `bypassSecurityTrustStyle`
  * `bypassSecurityTrustUrl`
  * `bypassSecurityTrustResourceUrl`
* or the old way of AngularJS to allow HTML user input
  * `$sce.trustAsHtml`
* or (also from AngularJS) these are probably universally dangerous when user input goes in:
  * `$eval`
  * `$evalAsync`

Would that be something you'd like to have around here?

**Comment by g0tmi1k** [comment]
Hello @bkimminich 
Yes, Yes it would!
Please could you open up a PR?

**Comment by bkimminich** [comment]
Cool! Which folder would you like to have it in? Should I make a list only for Angular and other frameworks would get their own file or just one generic `DangerousJavaScriptFrameworkFunctions.txt`?

**Comment by g0tmi1k** [comment]
I would throw it into `./Pattern-Matching/` - and if possible, split per framework (that way, they can be `cat * > DangerousJavaScriptFrameworkFunctions`) if the needs...

**Comment by g0tmi1k** [comment]
Merge'd
