### ISSUE TITLE
MySQL, SQL Injections

### ISSUE THREAD

**Issue by demidovakatya** [danielmiessler/SecLists#37]
http://pentestmonkey.net/cheat-sheet/sql-injection/mysql-sql-injection-cheat-sheet

**Comment by rojaster** [comment]
Is it a creation date or date of last material update - Tuesday, November 27th, 2007- ?

**Comment by demidovakatya** [comment]
I think it's the creation date.

**Comment by rojaster** [comment]
I think this material is not bad, but that's one is not the best.

**Comment by danielmiessler** [comment]
I think we have most of these in there already. If you look under SQL and don't see any of them, please submit them as a separate list and we'll add you to the credits. Thanks much!

**Comment by demidovakatya** [comment]
okay, thanks! :)
