### ISSUE TITLE
Add /apidocs/api-docs.json

### ISSUE THREAD

**Issue by milangfx** [danielmiessler/SecLists#375]
I came across this endpoint in the wild, it was called by a Swagger UI to render the documentation for an API.

Can we add this to one of the lists? I didn't want to open a PR as I don't know which file (maybe more than 1?) would be best.
Maybe Discovery/Web-Content/quickhits.txt? or Fuzzing/fuzz-Bo0oM.txt?
The latter one already has api/swagger-ui.html, swagger-ui.html, swagger.json, etc which are related.

**Comment by g0tmi1k** [comment]
Feel free to make a PR!

**Comment by NF997** [comment]
Would be cool if we could also add `/api-docs`.
E.g. OWASP Juice Shop hosts a swagger documentation under this path.
`SecLists/Discovery/Web-Content/swagger.txt` seems to be a good file to add these entries.
@g0tmi1k Do you agree?

**Comment by milangfx** [comment]
Sorry, I completely forgot about this issue. I've added them to `Fuzzing/fuzz-Bo0oM.txt`.
`Discovery/Web-Content/swagger.txt` has 4 lines, I don't think anyone uses that.

**Comment by g0tmi1k** [comment]
@NF997 - I do!
