### ISSUE TITLE
PHP code exec grep list missing three items

### ISSUE THREAD

**Issue by Harrison-Mitchell** [danielmiessler/SecLists#377]
https://github.com/danielmiessler/SecLists/blob/d19c482b7516838d456b12745ff02dd186b33a1e/Pattern-Matching/grepstrings-auditing-php.md#command-execution

The following also allow code exec in PHP:
- passthru()
- proc_open()
- popen()
- backticks: \`cmd\`

**Comment by drwetter** [comment]
They are in

https://github.com/danielmiessler/SecLists/tree/master/Pattern-Matching/Source-Code-(PHP)
, except backticks: `cmd` but maybe those can be merged ?

**Comment by g0tmi1k** [comment]
Feel free to open up a PR

**Comment by g0tmi1k** [comment]
Done! Thanks to @molangning
