### ISSUE TITLE
Can't open on Windows

### ISSUE THREAD

**Issue by AlexShepler** [danielmiessler/SecLists#392]
I tried to download the file onto my Windows machine and when I try to open or unzip the file it says "Windows cannot open the folder. The compressed (zipped) Folder 'C:\Download\Location' is invalied'" and I've also tried the git clone command as well.

**Comment by g0tmi1k** [comment]
Try using the non in-built zip manager (such as 7zip).

Also, git would be a better way to get it.
And Linux would be better still
