### ISSUE TITLE
Organization

### ISSUE THREAD

**Issue by jordan-wright** [danielmiessler/SecLists#4]
Let me preface by saying these two things:
* I appreciate the hard work you are putting into this - I'm excited to see this develop!
* Organization of things like this is tricky

That being said, I noticed that the organization of this repo wasn't standardized, and there may be some improvements that can be made. Here are some suggestions (in no particular order):
* Case standardization - ```"Discovery"```: vs ```"stress"```, etc. Might I suggest going all lower-caps, as this would be easier to traverse in a standard CLI environment?
* Why is there two "DNS" folders? One in ```/```, one in ```"Discovery/"```?
* Many of the items in ```"vuln/"``` are repeated (and expanded) in subsequent ```"Discovery/"``` files (e.g. see coldfusion)
* I personally can't see any use for the file ```pi_large.txt```, but please let me know if there is one!
* Repeated files (e.g. "alphanum_case.txt" found in both ```"stress/"``` and ```"Misc/"```
* In general, it seems as though many things that could be considered "subcategories" are found in the root folder. Though this interpretation is different for everyone, I personally find that moving things like ```"DNS/"``` and ```"URLs/"``` to the ```"Discovery"``` folder would make the root a bit more logically structured.

These were just a few suggestions after glancing at the repo. Feel free to change/disregard as you see fit. Thanks again for all the hard work!

**Comment by danielmiessler** [comment]
Yes, we're looking to do some major cleanup soon. Thanks for applying some pressure, Jordan.

**Comment by danielmiessler** [comment]
We're all cleaned up now, Jordan. Please check out the new structure and let us know what you think. Really appreciate the feedback.
