### ISSUE TITLE
XSS fuzz lists

### ISSUE THREAD

**Issue by vanderaj** [danielmiessler/SecLists#40]
Many of the XSS payload files are not directly consumable by fuzzing applications, such as Burp Intruder. I think it would be great if there were seperate fuzzing files to the discussion files. For example, Mario's XSS file is AWESOME and so advanced that it's akin to magic, but it takes a bit of work to use within tools. 

How best to help you guys with this?

**Comment by jhaddix** [comment]
I agree, but the context in that file is advantageous. How about make a stand alone fuzzing version and commit with a comment that one is better consumed by Burp and the other used as a reference?

**Comment by danielmiessler** [comment]
Yes please!

**Comment by danielmiessler** [comment]
Yes, that's a good idea. We should mark files as tool-ready or something within the name of the list.

**Comment by CrossSitePotato** [comment]
@danielmiessler @jhaddix I realize this issue is a little old, but I came across it today and thought the idea here is fabulous. I'd be happy to take a stab at this, that is, if you still want something. Is the solution you want really just make new fuzzing files that can be directly imported into tools (Burp and ZAP come to mind)?

**Comment by Beyarz** [comment]
Sounds like a good idea to me!

**Comment by pypetey** [comment]
Great idea.

**Comment by freddiebarrsmith** [comment]
This is a great idea.

**Comment by molangning** [comment]
Yo I am taking this up, but while looking through the lists I seed some repeated strings, specially ```//["'`-->]]>]</div>``` 

![Screenshot_2023-12-08_01-51-30](https://github.com/danielmiessler/SecLists/assets/133737702/d5bd35f6-8440-4cf9-bbfe-ea71b60710f9)

**Comment by molangning** [comment]
@g0tmi1k I think this can be closed

**Comment by Bilao600** [comment]
look at this Aviator software

look at this Aviator software that I had been trying to unlock for a very
long time, I did not receive





Le mar. 26 mars 2024 à 07:36, Mo Langning ***@***.***> a
écrit :
