### ISSUE TITLE
Missing very comon name.

### ISSUE THREAD

**Issue by unKn0wnUser453** [danielmiessler/SecLists#408]
Add "root" to /usr/share/seclists/Usernames/Names/names.txt

**Comment by g0tmi1k** [comment]
Feel free to open a PR

**Comment by CoccodrillooXDS** [comment]
@unKn0wnUser453, I've made a PR for you. 
CC: @g0tmi1k

**Comment by g0tmi1k** [comment]
Cheers @CoccodrillooXDS 

Closing
