### ISSUE TITLE
add dutch password wordlists

### ISSUE THREAD

**Issue by Kadeeli** [danielmiessler/SecLists#423]
I would like to make a contribution to the seclist password directory.
For my studies I generated a dutch passwordlist based on all the dutch
emails from the databreach collection #1 to #5. I also found a list of
dutch words which is generated based on a lot of scanned documents and
articles by other researchers. They are sorted on frequency. I hope its
good enough to be in there 

Dutch_passwordlist
https://www.dropbox.com/s/rbgmmtsqupawtfc/Dutch_passwordlist.txt?dl=0

Dutch wordlist
https://www.dropbox.com/s/z3d0di7to1yv3cc/Dutch_wordlist.txt?dl=0

**Comment by g0tmi1k** [comment]
Feel free to open up a PR!

**Comment by g0tmi1k** [comment]
Wooo! Cheers for the PR!
