### ISSUE TITLE
I want to consult a place

### ISSUE THREAD

**Issue by liujie1995gg** [danielmiessler/SecLists#429]
My English is not standard, the following generated by translation software
--------------------------
About the link
https://github.com/danielmiessler/SecLists/tree/master/Payloads/PHPInfo/phpinfo-metadata.jpg

How can I use this code in the JPG files? Direct access to the invoked download, cannot execute! Introduction: I am a small white is self-study, hope to receive the author's reply, thank you

**Comment by g0tmi1k** [comment]
Need to read the metadata.
