### ISSUE TITLE
what is the lowecase.txt is? we it have all the content from the main one?

### ISSUE THREAD

**Issue by rajeshk28** [danielmiessler/SecLists#436]

**Comment by g0tmi1k** [comment]
The main one being?

**Comment by rajeshk28** [comment]
I am talking regarding Raft lower case wordlists. Are they the same compared to other RAFT wordlists. Means is the content same of different

**Comment by g0tmi1k** [comment]
```
% cat raft-small-words.txt| tr '[:upper:]' '[:lower:]' | sort -u > raft-small-words-new.txt
% wc -l raft-small-words* | sort
   38267 raft-small-words-lowercase.txt
   38267 raft-small-words-new.txt
   43003 raft-small-words.txt
  119537 total
%
```

So yeah, same content - just with the duplicates from making it lowercase removed.

**Comment by g0tmi1k** [comment]
I wonder how much value it is then having the lowercase ones (I guess it depends on if its used in something which is case insensitive)

**Comment by molangning** [comment]
I surpose it is useful when you have a target that somehows transform everything into lowercases or mixed cases requests get a redirect to its lowercase version.
