### ISSUE TITLE
Typo in top-20-common-SSH-passwords.txt

### ISSUE THREAD

**Issue by jensregel** [danielmiessler/SecLists#438]
Typo in [https://github.com/danielmiessler/SecLists/blob/master/Passwords/Common-Credentials/top-20-common-SSH-passwords.txt](url)

`maintaince`

should be

`maintenance`

**Comment by g0tmi1k** [comment]
Feel free to open up a PR

**Comment by clem9669** [comment]
You can close it now ;) @g0tmi1k

**Comment by g0tmi1k** [comment]
Closing :)
