### ISSUE TITLE
Missing contributor for KeyHacks in CONTRIBUTORS.md

### ISSUE THREAD

**Issue by lc** [danielmiessler/SecLists#450]
Hey @g0tmi1k,

It looks like you're missing a contributor in here: https://github.com/danielmiessler/SecLists/blob/master/CONTRIBUTORS.md

This Keyhacks API [markdown](https://github.com/danielmiessler/SecLists/blob/master/Miscellaneous/web/keyhacks-api.md) in your project was taking directly from here: https://github.com/streaak/keyhacks however there's no thanks or contribution added to the CONTRIBUTORS.md as far as I can see(?). If you could check that'd likely be nice to do, thanks!

**Comment by g0tmi1k** [comment]
Please open up a PR

**Comment by lc** [comment]
Hey @g0tmi1k,

Is this format in the PR alright?

**Comment by g0tmi1k** [comment]
Yes it is :) Thank you again

**Comment by lc** [comment]
Awesome, thanks for your work on SecLists @g0tmi1k!
