### ISSUE TITLE
SAP wordlists update

### ISSUE THREAD

**Issue by chudyPB** [danielmiessler/SecLists#464]
Hi,

I have found almost 300 SAP Webdynpro endpoints that are not included in SecLists wordlists.

New endpoints:

https://github.com/chudyPB/sap-wordlist/blob/master/diff-seclists-myadditions.txt

Whole project and whole wordlist (it contains several different wordlists + my endpoints).

https://github.com/chudyPB/sap-wordlist
https://github.com/chudyPB/sap-wordlist/blob/master/sap-ultimate.txt

Best regards,
chudy

**Comment by g0tmi1k** [comment]
Please open up a pull request with it

**Comment by g0tmi1k** [comment]
Should now be fixed - thanks again @chudyPB
