### ISSUE TITLE
/Passwords/Default-Credentials whitespaces in listnames

### ISSUE THREAD

**Issue by maxkleinke** [danielmiessler/SecLists#469]
Hey,

big one right here :----). The files `Oracle EBS passwordlist.txt` and `Oracle EBS userlist.txt` in `/Passwords/Default-Credentials` contain whitespaces which causes bash to view the single words as elements when iterating the folders and writing them to a variable/array.

**Comment by g0tmi1k** [comment]
Please open a pull request with it!

**Comment by g0tmi1k** [comment]
Should now be fixed - thanks again @maxkleinke
