### ISSUE TITLE
More WPA lists

### ISSUE THREAD

**Issue by its0x08** [danielmiessler/SecLists#481]
Hello
I was giving some WPA cracking classes and needed some real short WPA wordlist. I was obligated to use rockyou.txt  to crack that particular WiFi. That took my student an hour to crack since rockyou.txt is a bit big for non GPU cracking and small show-offs.
So I suggest converting all password lists to WPA compatible by filtering less than 8 letter passwords and placing new lists inside SecLists/Passwords/WiFi-WPA/Misc/

**Comment by g0tmi1k** [comment]
Feel free to open a PR
