### ISSUE TITLE
Discovery/DNS content details

### ISSUE THREAD

**Issue by hss14** [danielmiessler/SecLists#482]
First I want to apologize that this is a stupid question. But I googled and could not find the answer.

I get the idea that these are possible subdomain names. One possible use case is subdomain enumeration. But what exactly does each file contain? Could someone please explain, or better, add a more detailed README file?

Thank you in advance!

> FYI: Contents of Discovery/DNS/
> - subdomains-top1million-5000/20000/110000.txt
> - deepmagic.com-prefixes-top500/50000.txt 
> - namelist.txt        
> - fierce-hostlist.txt 
> - shubs-stackoverflow.txt  
> - bitquark-subdomains-top100000.txt              
> - sortedcombined-knock-dnsrecon-fierce-reconng.txt  
> - shubs-subdomains.txt   
> - dns-Jhaddix.txt

**Comment by g0tmi1k** [comment]
So the files in https://github.com/danielmiessler/SecLists/tree/master/Discovery/DNS, are pre-written suggestions of possible subdomains (either commonly seen/guessed/from zone transfers/made up)

The idea being, you need to take the list, and throw it into a tool and that tool will check to see if that subdomain is valid.

What tool? Depends on what exactly you want - there are a LOT out there, and support/dev quickly changes with them all.
`gobuster` is a good start. But theres 100's if not 1,000 out there.
