### ISSUE TITLE
Which is the most detailed wordlist for directory brute force?

### ISSUE THREAD

**Issue by FaizanNehal** [danielmiessler/SecLists#483]
I cannot find a wordlist for directory brute force. Can you suggest me which one should I use for directory brute force with ffuf or gobuster?

**Comment by phreakcoder** [comment]
the one in /usr/share/wordlists/gobuster/directory-list-2.3-medium.txt it works most of the time

**Comment by g0tmi1k** [comment]
Any here are designed what your wanting ~ https://github.com/danielmiessler/SecLists/tree/master/Discovery/Web-Content

The bigger, the more it may find, but longer it will take.
Everything is a trade off
