### ISSUE TITLE
BiblePass wordlist

### ISSUE THREAD

**Issue by MusicGivesMeLife** [danielmiessler/SecLists#499]
I made an R script that generates a wordlist based on likely permutations of Bible verses.  The final list is split into several (currently 5) files by limiting each to a max of 3mil lines each.  I've actually used this list to help a local organization improve their security by demonstrating that passwords based off Bible verses are too predictable.

I would like to submit this list for possible inclusion.

[https://github.com/MusicGivesMeLife/BiblePass](https://github.com/MusicGivesMeLife/BiblePass)

**Comment by g0tmi1k** [comment]
Feel free to open up a PR!
