### ISSUE TITLE
Add HTTP request methods

### ISSUE THREAD

**Issue by arjunshibu** [danielmiessler/SecLists#507]
[http-methods.txt](https://github.com/danielmiessler/SecLists/files/5273369/http-methods.txt)

**Comment by clem9669** [comment]
Hey @arjunshibu ,

Great list !
I think this is not an issue. Make it a pull request 😀 

Cheers

**Comment by arjunshibu** [comment]
Will do😊

**Comment by g0tmi1k** [comment]
https://github.com/danielmiessler/SecLists/pull/519
