### ISSUE TITLE
Add new polyglots

### ISSUE THREAD

**Issue by danielmiessler** [danielmiessler/SecLists#51]
Reminder to myself to add this:  https://github.com/0xsobky/HackVault/wiki/Unleashing-an-Ultimate-XSS-Polyglot via @jhaddix

**Comment by jhaddix** [comment]
+1

**Comment by danielmiessler** [comment]
It was your find, great one.

**Comment by magnusstubman** [comment]
+1

**Comment by danielmiessler** [comment]
Added!
