### ISSUE TITLE
Unable to git clone

### ISSUE THREAD

**Issue by kacprzewski** [danielmiessler/SecLists#515]
after using git clone on gitbash or GitHub CLI this what shows up:
![1](https://user-images.githubusercontent.com/34382016/94854902-f2e40000-042d-11eb-94eb-2cd891b1c6e2.PNG)

the same problem is when I try to extract the file from .rar

Does Anybody know how to fix it?

sorry if this question was posted before but I couldn't find it

**Comment by robinminto** [comment]
Windows doesn't like the filenames added in commit 58f2b4db5373aec093bfa40da30a5af0344f5050. You should be able to check out cd9b3c6568602711d5f044112c55a790bf6d7392.

You can also checkout successfully with "Windows Subsystem for Linux" on Windows.
