### ISSUE TITLE
Let's add these EFF lists

### ISSUE THREAD

**Issue by danielmiessler** [danielmiessler/SecLists#529]
https://www.eff.org/dice

**Comment by g0tmi1k** [comment]
Feel free to open a pull request ;)

**Comment by cnotin** [comment]
Users have to use six words chosen randomly from the provided dictionary. Do we want to store the very long list of all possible combinations?
Or just the simple dictionary itself (which is basically the English dict!)?

**Comment by shoeper** [comment]
I don't think anyone wants to store 2^77 strings

**Comment by redstonedesigner** [comment]
> Feel free to open a pull request ;)

I felt free, so I did.
