### ISSUE TITLE
Add Donald Trump leaked passwords

### ISSUE THREAD

**Issue by shelld3v** [danielmiessler/SecLists#530]
Trump password has been hacked 2 times:
- 2016: `yourefired`
- 2020: `maga2020!`

I think some people will now use one of those as their passwords (if they love Trump). Since I don't know where should I add this to, I created this issue to let you know and add them if you feel interested

**Comment by weisk** [comment]
such a kind one you are :D

**Comment by shelld3v** [comment]
I love Trump but won't use that password for sure 🤣

**Comment by g0tmi1k** [comment]
Feel free to open up a pull request with it.

**Comment by shelld3v** [comment]
But what file?

**Comment by g0tmi1k** [comment]
I would go with : https://github.com/danielmiessler/SecLists/blob/master/Passwords/twitter-banned.txt
Because ~ https://github.com/danielmiessler/SecLists/commit/14128bab60c9eeb7c65ce5188f9e7aee56e0db23
History ~ https://en.wikipedia.org/wiki/Covfefe
