### ISSUE TITLE
DNS wordlists should not have multiple cases for the same word 

### ISSUE THREAD

**Issue by mubix** [danielmiessler/SecLists#553]
Noticed that a few of the DNS lists include case sensitive DNS like AutoDiscover and autodiscover. DNS is case insensitive unless I'm mistaken. So it's wasting the resolutions

**Comment by shoeper** [comment]
Here are the line counts for current files and with upper casing unique sort.

| as is   | sort -fu | difference |
|---------|----------|------------|
|  100000 |   100000 |          0 |
|   50000 |    49928 |         72 |
|     500 |      500 |          0 |
| 2178751 |  2171687 |       7064 |
|    2280 |     2280 |          0 |
|    1907 |     1907 |          0 |
|   64818 |    64721 |         97 |
|  484700 |   484699 |          1 |
|  102593 |   102582 |         11 |
|  114532 |   114441 |         91 |
|   19983 |    19966 |         17 |
|    4997 |     4989 |          8 |
| 3125061 |  3117700 |       7361 |

**Comment by mubix** [comment]
My apologies, I didn't mean to insinuate that anyone wasn't doing a good job, just suggesting improvement. I chose my words poorly. Thank you for doing the work to clear it up.
