### ISSUE TITLE
PR #559 supporting issue (as per CONTRIBUTING.md )

### ISSUE THREAD

**Issue by TAbdiukov** [danielmiessler/SecLists#560]
PR:  https://github.com/danielmiessler/SecLists/pull/559
Protocol for the reference, https://en.wikipedia.org/wiki/OBject_EXchange

Common paths references,

* http://dev.zuckschwerdt.org/openobex/wiki/ObexFtpServices
* http://www.pday.com.cn/technology/irda_documents/irmc_v1p1.pdf

* https://manualzz.com/doc/24948742
* https://manualzz.com/doc/922881/dcs-phfs-dw-user-guide

Rare paths references:

* https://www.hybrid-analysis.com/sample/0182620c4532fbf71d9333c45c67057c5157a43dcf110cf26a45e62d771f2c6c/5ef8b70ff791f948d1080422 
* https://seclists.org/pen-test/2006/Aug/339

* http://lists.unixcenter.ru/archives/mlug/2004-July/026116.html
* http://lists.unixcenter.ru/archives/mlug/2004-July/026118.html

* https://s3p.manualzz.com/store/data/024948742.pdf?key=7c38d81c1d38672e973debb671b3c68f&r=1&fn=24948742.pdf&t=1611075243638&p=86400

* https://archive.org/details/pdfy-k_NyjZisdngtL5Xt
* https://archive.org/details/pdfy--R42sHTAJgH01ZXT
* https://www.serasidis.gr/circuits/smscontrol/at_2003.pdf

* My own findings

P.S. some of the information is REALLY obscure :smile:

**Comment by shoeper** [comment]
"please use ONE of the following methods to submit them" - CONTRIBUTING.md

**Comment by g0tmi1k** [comment]
Please open up a pull request

**Comment by TAbdiukov** [comment]
I close my issue as the PR is merged (and I didn't realise it was OR, not AND - sorry about that :) @g0tmi1k @shoeper )
