### ISSUE TITLE
Add all 20th century anniversary dates

### ISSUE THREAD

**Issue by GraoMelo** [danielmiessler/SecLists#567]
From:  https://github.com/GraoMelo/SecLists/blob/master/Passwords/Common-Credentials/1900-2020.7z

Size compressed file: **4,8 KB**
Hash: 768b352b28ee11a6cbdffd614576f7e1431a5a818ae5677ab971bf6b918760e7 ( Sha256 ) 
Size uncrompress: **396 KB**

By @GraoMelo 
license MIT

Path suggestion: [link](https://github.com/danielmiessler/SecLists/tree/master/Passwords/Common-Credentials)
SecLists/
├── Passwords
├── ── Common-Credentials

request email sent today. ( to daniel.miessler and jason.haddix )

**Comment by g0tmi1k** [comment]
Please open up a pull request

**Comment by GraoMelo** [comment]
@g0tmi1k  pthe pr #581  was created.

thanks.

**Comment by GraoMelo** [comment]
Merged thanks Guys!
