### ISSUE TITLE
Add webpack.manifest.json

### ISSUE THREAD

**Issue by Faelian** [danielmiessler/SecLists#568]
Hello,

The file `webpack.manifest.json` has been immensely useful to me recently.
I have been able to retrieve the source code of the admin app, that was deployed using webpack (the file produced has a random name). The admin app source code contain secrets and functionalities, etc... You know the drill.

I think it would be a useful addition to the lists. Maybe `Discovery/Web-Content/big.txt` ?
I am not sure which file I should do a pull request to.

PS : thank a lot for this repo. I use it on every pentest. This is a blessing.

**Comment by righettod** [comment]
`big.txt` or `common.txt` from the `Discovery/Web-Content` folder are good candidates I think 😃

**Comment by g0tmi1k** [comment]
Please open up a pull request with it!

**Comment by g0tmi1k** [comment]
#570
