### ISSUE TITLE
File "contribute.json"

### ISSUE THREAD

**Issue by righettod** [danielmiessler/SecLists#576]
Hi,

Are you OK for a PR adding the entry `contribute.json` to the [common.txt](https://github.com/danielmiessler/SecLists/blob/master/Discovery/Web-Content/common.txt) dict ?

Sources:  
- https://infosec.mozilla.org/guidelines/web_security#contributejson
- https://www.contributejson.org/
- https://github.com/mozilla/contribute.json

If yes, I will submit a PR once the PR #573 will be merged or rejected.

Thanks a lot in advance 😃

**Comment by g0tmi1k** [comment]
Yes - feel free to open a PR!

**Comment by righettod** [comment]
Ok I will do it asap. Thanks a lot :)

**Comment by righettod** [comment]
PR #577  submitted 😃

**Comment by g0tmi1k** [comment]
PR #577 merged 😃

**Comment by righettod** [comment]
Thank you very much 💯
