### ISSUE TITLE
Please add git tags on releases

### ISSUE THREAD

**Issue by offensive-security** [danielmiessler/SecLists#59]
Firstly, thanks for sharing your code with the open-source world.

As you may or may not be aware, we have included your tool in our Kali Linux penetration testing distribution so it can be easily installed by our large user-base. You can follow the package development cycle here - http://pkg.kali.org/pkg/seclists

As the distribution includes hundreds of tools, keeping them updated is a significant undertaking. We would like to ensure that your tool is always kept as current as possible so that our users can benefit from the latest features and fixes. You could help us in this task immensely by tagging your releases here on GitHub. Tagging releases allows us to automate the process of checking for new releases, ensuring that tools get updated far more quickly.

Tagging can be included in your workflow very easily and would go a long way to helping us keep your tool updated in our distribution. The most common type of tag is the "lightweight" version as follows (where 0.3 is the new version number):

git-tag v0.3
git push --tags

Thanks!

**Comment by danielmiessler** [comment]
Ok, you should have a release now. Thanks for reaching out and including us in Kali!
