### ISSUE TITLE
Bug - installation progect

### ISSUE THREAD

**Issue by lucabigoni1992** [danielmiessler/SecLists#593]
**Describe the bug and expected behavior**

**To Reproduce**
1 oper cmd like asministrator
2 execute comand: _cd c:\temp_ (folder where i can write  wit all o.s. User)
2 execute comand: _git clone --depth 1 https://github.com/danielmiessler/SecLists.git_
3. See error

**example**

C:\temp>git clone https://github.com/danielmiessler/SecLists.git
Cloning into 'SecLists'...
remote: Enumerating objects: 64, done.
remote: Counting objects: 100% (64/64), done.
remote: Compressing objects: 100% (37/37), done.
remote: Total 9861 (delta 22), reused 55 (delta 20), pack-reused 9797
Receiving objects: 100% (9861/9861), 791.64 MiB | 8.12 MiB/s, done.
Resolving deltas: 100% (5135/5135), done.
error: invalid path 'Payloads/File-Names/traversal/..::..::;'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

the folder C:\temp\SecLists now exist, but it is empty

**Screenshots**
![Cattura](https://user-images.githubusercontent.com/62895248/114320964-ddf0d380-9b18-11eb-85d7-eeae885972d0.PNG)

**Version**
 - OS: Win10

**Comment by BMK91** [comment]
Same happens with me again.
The issue happens on 05/2020 also & still exist today. (On that time I individually cloned the folders).
@danielmiessler ..Please check...

**Comment by mietinen** [comment]
Sounds like an issue with git for windows.
These files are named in a way that they would cause problems with some programs and file systems.
Try doing `git config core.protectNTFS false`
> core.protectNTFS
> If set to true, do not allow checkout of paths that would cause problems with the NTFS filesystem, e.g. conflict with 8.3 "short" names. Defaults to true on Windows, and false elsewhere.

**Comment by g0tmi1k** [comment]
This isn't an issue with Seclist - rather than the OS. 

Closing
