### ISSUE TITLE
full 10 million password list?

### ISSUE THREAD

**Issue by My1** [danielmiessler/SecLists#614]
the "10 Million Password list" in common credentials has several top x files up to top 1 million, but there does not seem to be a full file. is that available somewhere?

**Comment by elitejake** [comment]
This is the one you're looking for: [xato-net-10-million-passwords.txt](https://github.com/danielmiessler/SecLists/blob/master/Passwords/xato-net-10-million-passwords.txt).

**Comment by My1** [comment]
but if the xato net us used for the "10-million-password-list-top-x" files then arent the sub lists of the xato list right next to it kinda duplicates?

**Comment by elitejake** [comment]
Oh sorry, I thought you were talking about _xato-net-10-million-passwords_. I too was unable to find the the complete _10-million-password-list_.
I did check if they are duplicates, turns out they are not. But they are _almost_ the same up to 100,000 lines.

**Comment by My1** [comment]
nope I meant the one in the common credentials folder :-)

**Comment by Ceazerbrowns** [comment]
Please somebody send me the commands for the👆

**Comment by g0tmi1k** [comment]
please do open up a merge reqest

**Comment by My1** [comment]
> please do open up a merge reqest

with what? I dont even know what the 10 Million password list even IS.

**Comment by ItsIgnacioPortal** [comment]
I have no idea of where @danielmiessler got that list from. The files were uploaded on commit [f50231d90afeff9738d34d3041381ec44b6b202e](https://github.com/danielmiessler/SecLists/commit/f50231d90afeff9738d34d3041381ec44b6b202e#comments), but there aren't any details there.

Unless Daniel remembers, this pursuit is pointless :p

**Comment by molangning** [comment]
I believe @danielmiessler got it from xato.net

Currently it is down but you can check its archives here

https://web.archive.org/web/*/https://xato.net/*
