### ISSUE TITLE
Missing credits for Gitrob signatures

### ISSUE THREAD

**Issue by michenriksen** [danielmiessler/SecLists#63]
Hey there,

I feel a bit shitty for opening this issue, but I am the creator of [Gitrob](https://github.com/michenriksen/gitrob) and I would really appreciate a Thanks and a reference to the tool in the README as the Gitrob file signatures have been included in SecLists [here](https://github.com/danielmiessler/SecLists/blob/master/Discovery/PublicSourceRepoIssues.txt).

Thanks for maintaining this awesome project. It is truly useful!

**Comment by danielmiessler** [comment]
Pretty sure I added you right after I asked you via email. Let me check.

**Comment by danielmiessler** [comment]
You were absolutely correct. It wasn't there. I must have forgotten to add it right as I was doing it. Many apologies. You are there now, as you should have been from the beginning.

Thanks for your great project!
