### ISSUE TITLE
add "___graphql" to "Discovery/Web-Content/graphql.txt"

### ISSUE THREAD

**Issue by han0x7300** [danielmiessler/SecLists#642]
Hi,

add "___graphql" to "Discovery/Web-Content/graphql.txt",please ?

Sources:

* https://www.gatsbyjs.com/docs/reference/graphql-data-layer/graphql-api/ 
* https://www.gatsbyjs.com/docs/tutorial/part-4/

Thanks

**Comment by g0tmi1k** [comment]
Merged in now.

Thanks!
