### ISSUE TITLE
Git clone failing here.

### ISSUE THREAD

**Issue by slagazor** [danielmiessler/SecLists#682]
Should I not be able to just git clone URL ? 

Am I missing a download link? I apologize I'm just sort of new to this area.

**Comment by karliszigurs** [comment]
http://www.catb.org/~esr/faqs/smart-questions.html

**Comment by slagazor** [comment]
Wow that was sooooo helpful. Just like when I first started learning linux in the 90's. The smelly guys in the redhat club would basically just say RTFM to any question. Whilst the slackware guys would take you under their wing and help when you got stuck make sure you got your box up and running. At worst they would point you to a how-to or at least suggest the right keywords to search on. 

Your gate keeping is obnoxious.

**Comment by karliszigurs** [comment]
I thought you were 14.

This is kinda embarrassing. You still have not shared anything that we can
help you with.

**Comment by slagazor** [comment]
I was looking for this "https://github.com/danielmiessler/SecLists.git" and couldn't find it previously.

**Comment by karliszigurs** [comment]
Ok, so you are 14. Fair enough.

**Comment by slagazor** [comment]
asshole much?

**Comment by karliszigurs** [comment]
Calm down and reflect that you blasted a mailing list for your inability to
use github.

**Comment by PinkDev1** [comment]
@karliszigurs you're being unnecesarily mean. This is most likely someone who is just now entering cybersecurity and found this repo by chance. Would it really have been that hard to just give a _short_ explanation as to how to `git clone`?

Sorry about that @slagazor, if you can't solve a problem on your own, don't hesitate in opening an issue. But you're likely to get snarky responses if people don't _see_ that you've tried to fix it _on your own_ first.

**Comment by slagazor** [comment]
Thank you I appreciate that. 

I've actually worked in it my entire life I was online in the '80s. 

I'm just retired now and all the new changes are just overwhelming. 

I've successfully used git clone before but sometimes an app will just have well n shitty install instructions. 

For instance I just installed sabnzbd but I have no idea how to proceed once it's cloned.
