### ISSUE TITLE
Missing /opcache/ directory in Web-Content

### ISSUE THREAD

**Issue by blacklist-arcc** [danielmiessler/SecLists#683]
On a recent pentest i noticed a webserver using php opcache gui (https://github.com/amnuts/opcache-gui)
The unprotected gui shows up some jucy information about the running web server and could be useful for further analysis. The `/opcache/` name is not included in any wordlist. Is there a chance to include this directory name in one of the Web-Content lists?

Cheers.

**Comment by g0tmi1k** [comment]
Thanks for the suggestion.

Please do open up a pull request with it, and we can accept it :)

**Comment by g0tmi1k** [comment]
I believe its now merged in - thanks for taking the time to make the pull request!
