### ISSUE TITLE
Missing default passwords

### ISSUE THREAD

**Issue by Wernfried** [danielmiessler/SecLists#691]
In the default password list, I would miss the standard default password "Changeme_123" from Huawei.

Google for ```Changeme_123 Huawei```, then you will get system documentation of various systems and very many are using "Changeme_123" as default password

**Comment by drwetter** [comment]
I am not maintainer of this. But to ease matters: why don't you just suggest a PR?

**Comment by g0tmi1k** [comment]
Thanks for the suggestion.

please do open up a pull request with it, and we can accept it :)

**Comment by elitejake** [comment]
I found `Changeme_123` in [`default-passwords.csv#L1052`](https://github.com/danielmiessler/SecLists/blob/master/Passwords/Default-Credentials/default-passwords.csv#L1052).

**Comment by g0tmi1k** [comment]
Closing!
