### ISSUE TITLE
Is there a way for me NOT to download the Payloads folder of this repository?

### ISSUE THREAD

**Issue by JohnMackYouTube05** [danielmiessler/SecLists#694]
Hi, yes, I’d like to *not* download a bunch of ZIP bombs on my computer while I’m trying to do pen testing, thanks. I used WSL to clone the repository, and now Windows Defender is going apeshit with like 200 different virus detections

**Comment by Halbachb** [comment]
Just turn off Defender

**Comment by elitejake** [comment]
Or add the repo folder to the Defender's exclusion list.

**Comment by drwetter** [comment]
use Linux!

**Comment by elitejake** [comment]
Or fork the repo and delete the directory.

No `Payloads` directory in this fork I created: `https://github.com/elitejake/SecLists/tree/without-payloads`.

**Comment by PinkDev1** [comment]
lmao

**Comment by g0tmi1k** [comment]
In short, no there isn't a nice way without changing your setup!

Either: 

- Disable the protection
- Allow it to exits on the protection
- Use a different OS
- Use a different fork of SecList
- Download via zip/tar and then delete the folder inside the compress file
