### ISSUE TITLE
merged.txt.tar not found

### ISSUE THREAD

**Issue by AresS31** [danielmiessler/SecLists#70]
Hi,
I cannot find the merged.txt.tar which is supposed to be the archived with all the different password lists sorted.
Best,
Alex

**Comment by wadeharrell** [comment]
https://github.com/danielmiessler/SecLists/commit/9b8e66e6421a579dadae38fe3550be3967973f3a

it was removed
the readme was not updated though

**Comment by AresS31** [comment]
Could you please upload the latest version of the merged list somewhere and link it so we can download it freely? :)

**Comment by tstephansen** [comment]
You can download it from the repository's history. https://github.com/danielmiessler/SecLists/blob/601038eb4ea18c97177b43a757286d3c8a815db8/Passwords/merged.txt.tar.gz

**Comment by dethmourne** [comment]
It's not clear - why was this issue closed? The merged file is still clearly referenced by the README.
