### ISSUE TITLE
Add "Cook" to related projects in the README

### ISSUE THREAD

**Issue by ItsIgnacioPortal** [danielmiessler/SecLists#711]
> An overpower wordlist generator, splitter, merger, finder, permutator, encoder, decoder.. Frustration killer. Customizable. The Wordlist Framework. 

https://github.com/giteshnxtlvl/cook

I'm sure someone here will find it handy :p

**Comment by g0tmi1k** [comment]
It might just be my untrained eyes, but that gist doesn't look like it actually says where the data comes from?

"original 41G stash"

maybe the magnet url would be more useful than the web-archive telling people to look up
