### ISSUE TITLE
Interested in default credentials?

### ISSUE THREAD

**Issue by michenriksen** [danielmiessler/SecLists#75]
Hey there,

I recently released a [simple tool](https://github.com/michenriksen/searchpass) to quickly find default creds for network devices, web applications, etc. and I was wondering if the file with all the creds would be a good addition to this project as well?

The file is in JSON format. Take a look at it [here](https://github.com/michenriksen/searchpass/blob/master/credentials.json).

Edit: Maybe I should mention that I did not compile this list myself; it was obtained from [cirt.net](https://cirt.net/passwords).

**Comment by whoot** [comment]
Hey,

this list is already in Seclists.
See [here](https://github.com/danielmiessler/SecLists/blob/master/Passwords/default-passwords.csv)

**Comment by michenriksen** [comment]
Oh, I didn't notice that one. However the list from cirt.net is bigger; it contains 2077 credentials while the file you mention contains 1638.

**Comment by whoot** [comment]
You are right, seems like some entries are missing.
For example the [3M - Volition](https://cirt.net/passwords?vendor=3M) has two entries, which can be found in the referenced documentation, too.
Maybe you can update the csv on SecLists with the missing entries?

**Comment by michenriksen** [comment]
Yeah, that would probably be the way to go. I can do that when I get a 👍  from one of the project owners.

**Comment by michenriksen** [comment]
Went ahead and made Pull Request #76 ¯\_(ツ)_/¯
