### ISSUE TITLE
Unable to checkout working tree in git clone complete

### ISSUE THREAD

**Issue by Rajar01** [danielmiessler/SecLists#753]
Cloning into 'SecLists'...
remote: Enumerating objects: 11021, done.
remote: Total 11021 (delta 0), reused 0 (delta 0), pack-reused 11021
Receiving objects: 100% (11021/11021), 834.50 MiB | 1.97 MiB/s, done.
Resolving deltas: 100% (5941/5941), done.
error: invalid path 'Payloads/File-Names/traversal/..::..::;'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by ItsIgnacioPortal** [comment]
I'm thinking of making that folder (`traversal`) into a zip so it's easier to contribute to this project from Windows. How does that sound @g0tmi1k ?

**Comment by Rajar01** [comment]
@ItsIgnacioPortal So how i can install this command with git clone.

**Comment by ItsIgnacioPortal** [comment]
To be honest, I don know. I've chosen to just clone this repository in Debian, using [WSL](https://docs.microsoft.com/en-us/windows/wsl/about)

**Comment by Rajar01** [comment]
Okay thanks you for your guide sir, @ItsIgnacioPortal  🙏
