### ISSUE TITLE
"1.4 billion password breach compilation wordlist" 404's

### ISSUE THREAD

**Issue by ryanwohara** [danielmiessler/SecLists#758]
The link provided by this document is no longer available:
https://github.com/danielmiessler/SecLists/blob/master/Passwords/url-to-download-passwords.md

**Comment by Technetium1** [comment]
I would like to second this issue.

**Comment by ItsIgnacioPortal** [comment]
#775 fixes this

**Comment by g0tmi1k** [comment]
This should be fixed now, thanks to @noraj & @ItsIgnacioPortal
