### ISSUE TITLE
Seclist refusing to clone into my kali

### ISSUE THREAD

**Issue by KingTomasi** [danielmiessler/SecLists#761]
Good day Daniel
Each time I try to git clone the seclist repo, it is extremely slow and then times out, leaving this error message as a result;

┌──(kali㉿kali)-[~/Documents/CTF]
└─$ git clone https://github.com/danielmiessler/SecLists.git
Cloning into 'SecLists'...
remote: Enumerating objects: 11021, done.
error: 1276 bytes of body are still expectedMiB | 181.00 KiB/s 
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

Please is there a solution to this?

**Comment by ItsIgnacioPortal** [comment]
Can you clone other repositories?

**Comment by KingTomasi** [comment]
Yes, I can clone other repositories
I just cloned sublist3r this morning
Thanks for your prompt response

**Comment by ItsIgnacioPortal** [comment]
Try cloning this repository again. If that fails, try updating git: `sudo git update`

**Comment by righettod** [comment]
Hi,

The problem is not present on a Ubuntu:

![image](https://user-images.githubusercontent.com/1573775/172055368-6aa35ac2-eb0a-4ed3-85de-6bf796ff735d.png)

**Comment by righettod** [comment]
No problem on a Kali 2022.2 too:

![image](https://user-images.githubusercontent.com/1573775/172055865-fdf254d5-e153-43c5-82ac-1ea725be29a9.png)

**Comment by KingTomasi** [comment]
I have the same version of git and the latest Kali version as well, what
else could be the problem?

**Comment by righettod** [comment]
I really do not know.

I retried after fully updading the Kali and I still not have error cloning the repository...

**Comment by rf-peixoto** [comment]
I had no problems here. You can try other methods of installing the repository besides git. Examples: https://kalilinuxtutorials.com/seclists-security-testers/

**Comment by KingTomasi** [comment]
Thank you so much, I was able to download the zip file directly through the
link you provided.
Have a lovely day

**Comment by g0tmi1k** [comment]
You should be able to `apt install seclists` on Kali.

I'm guessing whatever partition you are trying todo it on, in in a format (e.g. fat32, NTFS, EXT4) which doesn't like "something".

**Comment by BerenBoden** [comment]
First, turn off compression:
`git config --global core.compression 0
`
Then do a partial clone to truncate the amount of info coming down:
`git clone --depth 1 https://github.com/danielmiessler/SecLists
`
The change into the directory and get the rest
`cd Seclists && git fetch --unshallow`
