### ISSUE TITLE
Add XSS detection tool - Cyclops

### ISSUE THREAD

**Issue by v8blink** [danielmiessler/SecLists#764]
Name: Cyclops
Type:Discovery/XSS
Description: The Cyclops is a web browser with XSS detection feature, it is chromium-based xss detection that used to find the flows from a source to a sink.
github:https://github.com/v8blink/Chromium-based-XSS-Taint-Tracking

**Comment by ItsIgnacioPortal** [comment]
I don't think this is related to seclists...

**Comment by g0tmi1k** [comment]
Hi @v8blink 
This appears to be a tool, rather than a file of values?

However, the README has a table of values, is that what you are wanting to be added?

**Comment by v8blink** [comment]
Hi, @g0tmi1k 
Thank you for your reply.

Yes, it is a tool --- a web browser with XSS detection feature. 
Is there a slot for security tools in the SecList? I want to add my tool.
https://github.com/v8blink/Chromium-based-XSS-Taint-Tracking/blob/main/README-en.md

Of course, the table in README is very useful for detecting XSS，I wish it is  added.

**Comment by g0tmi1k** [comment]
This is more about lists of words, rather than a list of tools - sorry!
