### ISSUE TITLE
SecLists refusing to clone on Windows

### ISSUE THREAD

**Issue by SniffyMcTasty** [danielmiessler/SecLists#770]
I'm trying to clone the repo into Windows, but after cloning, I get an error telling me that checkout could not be completed:

![image](https://user-images.githubusercontent.com/68755892/174820717-ab0e78fb-4420-4aea-8b93-9277d6069ce3.png)

I then tried the proposed solution of `git restore --source=HEAD :/` but ended up getting pretty much the same thing:

![image](https://user-images.githubusercontent.com/68755892/174821462-9364e746-bddb-4b8e-a674-8e67fa5e29c7.png)

**Comment by ItsIgnacioPortal** [comment]
I'm trying to fix this issue. Try: `git clone -b i770 https://github.com/ItsIgnacioPortal/SecLists/` and tell me if that works.

**Comment by Silly26** [comment]
![image](https://user-images.githubusercontent.com/8854060/178124240-1da5f15e-b967-4917-8abd-f07a5de9ddfe.png)

I'm getting a failure to clone as well, although not with the filename length.

**Comment by ItsIgnacioPortal** [comment]
@Silly26 Look at the comment above yours.

**Comment by Silly26** [comment]
@ItsIgnacioPortal Thanks for the reply. The i770 branch takes care of the issue. 

Thank you!
