### ISSUE TITLE
List types fix

### ISSUE THREAD

**Issue by danielaltamirano1993** [danielmiessler/SecLists#772]
List types include user names, passwords

**Comment by g0tmi1k** [comment]
Hello @danielaltamirano1993 

I'm not sure exactly what you mean.
Could you explain it a little more?

**Comment by g0tmi1k** [comment]
Are you able to give more information @danielaltamirano1993 ?

**Comment by danielaltamirano1993** [comment]
I'm sorry for leaving the thread open. This code has grown too much... I have read your message and I will try to look for the problem I had found, although I see it better in passing.
