### ISSUE TITLE
please add this Unpublicly Paths in seclist that can leads to Mass Account Takeover And Sql on Oracle E-Business.

### ISSUE THREAD

**Issue by un9nplayer** [danielmiessler/SecLists#787]
Vulnerable Oracel Database login path :  /OA_HTML/AppsLocalLogin.jsp

![1](https://user-images.githubusercontent.com/75741506/176918051-d2145a27-2f2f-4740-8016-c040d8f6064e.PNG)

Vulnerable Create User Path : /OA_HTML/ibeCAcpSSOReg.jsp
an attacker can create a new user and get access to the database as a low user which is supposed not to be happening.

![2](https://user-images.githubusercontent.com/75741506/176918612-96ec2deb-9a77-47f1-8dbe-49fc4e66ac87.PNG)

after that Attackers can take full access and leak mass user data publicly.

![3](https://user-images.githubusercontent.com/75741506/176919345-3117b062-904f-42b2-86d7-925b4c023781.PNG)

so, please add both paths in seclist in discovery for web-find.

**Comment by g0tmi1k** [comment]
Feel free to make a pull request

**Comment by ItsIgnacioPortal** [comment]
> Feel free to make a pull request

I suspect that they made this issue because of the size of this repo; Some people don't want to have to clone 1.6GBs to be able to contribute :p

**Comment by x0rld** [comment]
> > Feel free to make a pull request
> 
> I suspect that they made this issue because of the size of this repo; Some people don't want to have to clone 1.6GBs to be able to contribute :p

well now you can do directly on github without cloning it

**Comment by stampyzfanz** [comment]
Also, try pressing the period key on a repository's homepage to use a web version of VS Code that contains the repository's content.

**Comment by sumayanavha** [comment]
Hi sir.. sorry needed the order please cancel the order 🙏

**Comment by g0tmi1k** [comment]
Done (thanks to @molangning )
