### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by kgryte** [danielmiessler/SecLists#80]
Looking through the project and the issues, I was unable to find a license. Can one be added to the project? Otherwise, cannot use anything until usage restrictions are known.

**Comment by MikeDawg** [comment]
https://www.owasp.org/index.php/Projects/OWASP_SecLists_Project    

Name: OWASP SecLists Project (home page)
Purpose: SecLists is a collection of multiple types of lists used during security assessments. List types include usernames, passwords, URLs, sensitive data grep strings, fuzzing payloads, and many more.
The goal is to enable a security tester to pull this repo onto a new testing box and have access to every type of list that may be needed.

License: Creative Commons Attribution ShareAlike 3.0 License (best for documentation projects)
who

**Comment by kgryte** [comment]
Thanks!
