### ISSUE TITLE
Seclists mirror

### ISSUE THREAD

**Issue by Albonycal** [danielmiessler/SecLists#844]
Hey! Thank you for making this,

I find downloading from github very slow, so I've made a mirror for seclist here: 

https://mirror.albony.xyz/hacks/seclists.zip

The mirror is hosted in India.

If you wish to add it to the readme feel free to :sweat_smile:

**Comment by machariavck** [comment]
Thanks man

**Comment by g0tmi1k** [comment]
Thanks for the suggestion, however, its not something we can update.
