### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by Jetrom17** [danielmiessler/SecLists#848]
Hello! I'm creating a project that involves using the "Crunch" software. Would you like to be able to create a folder here as well where it contains endless possibilities? The idea is that the security professional uses what is already ready, made by volunteers who used their computational power to generate infinite possibilities.

New Project: `https://github.com/Jetrom17/Dictionary`

Folder: `SecLists/Number/number_6.txt` = Inside the number folder and the "_6.txt" indicates that it contains only 6 digit numbers.

Before I contribute, I wanted to hear from you. For now I'm working on it myself. Also, there are files or something like that, which only contain numbers. The idea is not to just generate numbers or spend time with many possibilities that would spend more than two hours.

**Comment by ItsIgnacioPortal** [comment]
I'm not sure I understand. What exactly do you want us to do? If you want to add lists to the project you can make a pull request.

**Comment by Jetrom17** [comment]
> I'm not sure I understand. What exactly do you want us to do? If you want to add lists to the project you can make a pull request.

Ok. Thanks.
