### ISSUE TITLE
Frequency count is zero for PIN=8068.

### ISSUE THREAD

**Issue by TheRammer** [danielmiessler/SecLists#862]
The next lowest frequency count is 36, so a count of zero seems incorrect (or the perfect 4-digit PIN).

https://github.com/danielmiessler/SecLists/tree/master/Passwords/Common-Credentials)/four-digit-pin-codes-sorted-by-frequency-withcount.csv

**Comment by g0tmi1k** [comment]
- It is the last value.
- MR: https://github.com/danielmiessler/SecLists/issues/169
- Source: https://www.reddit.com/r/hacking/comments/7ujzkf/complete_list_of_four_digit_pins_ranked_in_order/
- File history: https://github.com/danielmiessler/SecLists/commits/master/Passwords/Common-Credentials/four-digit-pin-codes-sorted-by-frequency-withcount.csv

May want to ask the original author for more information about it.
