### ISSUE TITLE
Add image/jpg to content-type.txt

### ISSUE THREAD

**Issue by nirzaa** [danielmiessler/SecLists#868]
Hi,

Could you please add image/jpg to:
https://github.com/danielmiessler/SecLists/blob/master/Miscellaneous/web/content-type.txt
You have image/jpeg already there, but this might be helpful too, thanks!

**Comment by elitejake** [comment]
But, `image/jpg` is not a valid MIME type. Using it can [cause issues in browsers](https://stackoverflow.com/questions/33692835/is-the-mime-type-image-jpg-the-same-as-image-jpeg).

`image/jpeg` is the MIME type of JPEG.

**Comment by nirzaa** [comment]
> But, `image/jpg` is not a valid MIME type. Using it can [cause issues in browsers](https://stackoverflow.com/questions/33692835/is-the-mime-type-image-jpg-the-same-as-image-jpeg).
> 
> `image/jpeg` is the MIME type of JPEG.

So confusing... thanks for the clarification mate
