### ISSUE TITLE
Add list of Files Extensions

### ISSUE THREAD

**Issue by adilnbabras** [danielmiessler/SecLists#880]
[files-ext.txt](https://github.com/danielmiessler/SecLists/files/11524464/files-ext.txt)

**Comment by g0tmi1k** [comment]
Sounds good please do open up a pull request!

**Comment by molangning** [comment]
Where is this from? I cant find it in the repo but the link points to somewhere in the repo...

**Comment by molangning** [comment]
https://github.com/danielmiessler/SecLists/blob/master/Fuzzing/files-ext.txt is the exact same as the file posted here
@g0tmi1k you should be able to close this

**Comment by g0tmi1k** [comment]
Good catch @molangning 

In that case, closing!
