### ISSUE TITLE
There is a mirai botnet in these tool

### ISSUE THREAD

**Issue by Anas68755** [danielmiessler/SecLists#884]
Open the directory passwords/malware

**Comment by apoorvagora** [comment]
can someone verify?

**Comment by markoverholser** [comment]
It is very clearly just a text file with usernames and passwords _used by_ the Mirai botnet. There are no scripts or binary files in that directory.

**Comment by sparkle666** [comment]
😂😂

**Comment by g0tmi1k** [comment]
Closing as its offtopic
