### ISSUE TITLE
Add OMSAgent to LFI

### ISSUE THREAD

**Issue by nekonugget** [danielmiessler/SecLists#891]
Hi! Little collection of paths for the linux OMS agent which can be useful in LFIs.
Paths just taken from docs at time of writing - might add manual
https://github.com/nekonugget/lfi-stuff/blob/main/OMI-Agent-Linux.txt

**Comment by g0tmi1k** [comment]
Sounds good - please do open a pull request !

**Comment by g0tmi1k** [comment]
Done!
