### ISSUE TITLE
Add humans.txt and security.txt files to Web-Content discovery file lists

### ISSUE THREAD

**Issue by phillipdade** [danielmiessler/SecLists#893]
The following files should be added to the raft-*-files.txt list:

humans.txt
security.txt

These files would likely reside within the .well-known directory so maybe should be added in there too, but not sure if these file lists are suitable location

.well-known/humans.txt
.well-known/security.txt

**Comment by karliszigurs** [comment]
why?

**Comment by g0tmi1k** [comment]
Why the `raft-*` lists?

**Comment by ItsIgnacioPortal** [comment]
Please keep in mind that the source for the raft-* wordlists is the [Google RAFT project](https://code.google.com/archive/p/raft/). Perhaps SecLists/Discovery/Web-Content/common.txt would be better suited for these contributions.

common.txt already has `.well-known/security.txt`, so all that would be left to add is `.well-known/humans.txt`.
For context, see: https://humanstxt.org/

**Comment by g0tmi1k** [comment]
@phillipdade Woudl you like to add this to a MR?

**Comment by g0tmi1k** [comment]
Done (Thanks @molangning )
