### ISSUE TITLE
Turkish router passwords

### ISSUE THREAD

**Issue by barisbogdan** [danielmiessler/SecLists#898]
I have found some default password for routers in Turkey.
```
turktelekom
ttnet
superonline
vodafone
turknet
admintelecom
``` 
There's couple that I didn't included, because they are already in default passwords list.

**Comment by ItsIgnacioPortal** [comment]
@barisbogdan could you tell us which router brands these passwords are for? I think they could be a great contribution for a new folder in this project.

@g0tmi1k what's your opinion on adding a collection of default router passwords to this repo? Many of these default passwords can already be found publicly on the internet, so we wouldn't be exposing any secrets. They could also be of use to on-premises penetration testers.

I'm thinking of a file-structure like this:
```
SecLists
	Passwords
		Default-Credentials
			Routers
				tp-link_default_passwords.txt
				cisco_default_passwords.txt
				synology_default_passwords.txt
				asus_default_passwords.txt
				...
```

**Comment by barisbogdan** [comment]
/

**Comment by barisbogdan** [comment]
@ItsIgnacioPortal sorry for late response. I just have too much work I need to do for school.

The answer for question is a bit confusing. Turktelekom sells different brands of routers. I guess any router bought from Turktelekom is comes with password turktelekom.

**Comment by g0tmi1k** [comment]
@barisbogdan Thanks for the suggestion - please do open a PR!

@ItsIgnacioPortal I love the idea - wanna make it happen?

**Comment by barisbogdan** [comment]
Alright, I'll open a PR for that!
