### ISSUE TITLE
Yahoo mail account password

### ISSUE THREAD

**Issue by Darlingpanay** [danielmiessler/SecLists#903]
https://github.com/danielmiessler/SecLists/blob/395c945627196b6172e6e83a014c964f805e8d48/Discovery/Web-Content/common.txt#L4219  I want to hack yahoo mail to my boyfriend

**Comment by 1120236** [comment]
اريد اترجع حسابي القديم على انستغرام

**Comment by 1120236** [comment]
https://instagram.com/lexoooana?igshid=MzRlODBiNWFlZA==

**Comment by ItsIgnacioPortal** [comment]
The contributors of this project do not aim to aid potential criminals in invading devices they're not authorized to test. Please do not open issues requesting for assistance in committing criminal acts, and do not attempt to use the lists in this project for any illicit activities.

**Comment by g0tmi1k** [comment]
This is off topic for this project.
