### ISSUE TITLE
Help needed on file cleaning

### ISSUE THREAD

**Issue by molangning** [danielmiessler/SecLists#928]
I cleaned some files but skipped some files due to some files being for humans to read or is needed.

Can you please check it out if the changes are needed?

Thanks

~~https://github.com/molangning/SecLists/tree/patch-1~~ Deleted branch

**Comment by molangning** [comment]
script has many detections in raft wordlists
Pattern-Matching/dangerous-functions-angular.txt has comments

**Comment by g0tmi1k** [comment]
Hi @molangning 
I'm not sure whats been asked here - could you give some more information?

**Comment by molangning** [comment]
I forgot what was this surposed to be but I think I was trying clean raft?
