### ISSUE TITLE
Automated repository size listing

### ISSUE THREAD

**Issue by molangning** [danielmiessler/SecLists#937]
Idea: git clone size will get updated dynamically on push 
size can be retrieved through calls to github api in this format: `https://api.github.com/repos/USERNAME/REPOSITORY`

This is in reference to PR #779 

> I see it as another thing to maintain and update.
> Could this be automated?

Patches will be made in https://github.com/molangning/SecLists/tree/patch-1

**Comment by g0tmi1k** [comment]
Done!

**Comment by molangning** [comment]
Ayo this doesnt look right

![Screenshot_2023-11-29_18-59-30](https://github.com/danielmiessler/SecLists/assets/133737702/18fb4009-fab4-43fe-a4e6-0b87196fb8ce)
