### ISSUE TITLE
More xss wordlists

### ISSUE THREAD

**Issue by molangning** [danielmiessler/SecLists#950]
Found some great XSS wordlists
[xss-payload-list](https://github.com/payloadbox/xss-payload-list) in readme
[https://github.com/OWASP/EnDe](EnDe), specifically these links
```
https://github.com/OWASP/EnDe/blob/master/xss.mario.xml
https://github.com/OWASP/EnDe/blob/master/xssAttacks.xml
https://github.com/OWASP/EnDe/blob/master/xss.h4k.xml
https://github.com/OWASP/EnDe/blob/master/xss-evation.txt
```

I may add them if I can, but if anyone here wants to feel free to do so

**Comment by molangning** [comment]
xss mario from source
https://web.archive.org/web/20080108081352/http://mario.heideri.ch/xss.xml

**Comment by g0tmi1k** [comment]
I believe this has now been merged in ? Can be closed @molangning ?

**Comment by molangning** [comment]
I haven't seperated them into human and robot friendly versions yet so just keep them open for now.
