### ISSUE TITLE
https://www.tiktok.com/@zer0___73?_t=8iHxrs2WEJK&_r=1

### ISSUE THREAD

**Issue by Yaazir2005** [danielmiessler/SecLists#954]
https://github.com/danielmiessler/SecLists/blame/c8770277355ebb85737b97f6e5ac35f7cf2a387f/Discovery/Web-Content/dutch/new/13.txt#L4325

**Comment by Yaazir2005** [comment]
https://www.tiktok.com/@zer0___73?_t=8iHxrs2WEJK&_r=1

**Comment by Yaazir2005** [comment]
https://www.tiktok.com/@zer0___73?_t=8iHxrs2WEJK&_r=1

**Comment by molangning** [comment]
Why did you post these?

**Comment by g0tmi1k** [comment]
Closing due to spam
