### ISSUE TITLE
Consolidate language lists under appropriate language

### ISSUE THREAD

**Issue by emmanuel-londono** [danielmiessler/SecLists#958]
Would it be a good idea to move lists written in a certain language to that language folder, in Passwords for example. There are dutch, german and french lists in the same flat directory.

That could give people ideas to add lists for their respective culture/language.

**Comment by molangning** [comment]
It would be a good idea, but determining if a password is english or german is a hard job to do.

This issue should have been touched on before so if I find it I will mention it here

**Comment by molangning** [comment]
It's #462

**Comment by molangning** [comment]
You could try importing the list over, I'm sure everyone will appreciate it

**Comment by g0tmi1k** [comment]
@emmanuel-londono I would love it if someone could do that - feel free to have a go and open up a PR

**Comment by molangning** [comment]
@g0tmi1k @emmanuel-londono This issue can be closed, as it is imported in #979

**Comment by fansite101** [comment]
good

**Comment by kiratutech** [comment]
it would be ,
