### ISSUE TITLE
Adding lists of HTTP Request/Response headers

### ISSUE THREAD

**Issue by craSH** [danielmiessler/SecLists#96]
Hi there,

I'm working to get some decent lists of HTTP request and response headers, as well as examples for each for this repo. I've started my work here: https://github.com/craSH/SecLists/commits/http-headers

Before I do a PR, I was wondering if you had suggestions for organizing the data - e.g. should I create a new subdirectory under Miscellaneous, keep them as separate files like they are now, or do you have another suggestion? I'd like to keep the structure as organized as possible, but I don't think there's any agreed upon standard for that with the repo at this moment (e.g. some things have comments above certain payloads, etc.)

Thanks!

**Comment by g0tmi1k** [comment]
Currently there isn't any structure (WIP!)
I would make a new folder for it, and submit a PR...
