### ISSUE TITLE
Adding some NoSQL fuzzing lists

### ISSUE THREAD

**Issue by ZonkSec** [danielmiessler/SecLists#97]
I came to seclists looking for some nosql / mongo injection lists and couldn't find anything. 

Ended up finding the following and got some good use out of it:
https://github.com/cr0hn/nosqlinjection_wordlists/blob/master/mongodb_nosqli.txt

Figured it could be a nice addition :)

**Comment by jhaddix** [comment]
added: https://github.com/danielmiessler/SecLists/blob/master/Fuzzing/NoSQL.txt
