### ISSUE TITLE
[Question]: Which 10k password list should I use?

### ISSUE THREAD

**Issue by lonix1** [danielmiessler/SecLists#986]
I was very happy to find this repo: thanks for aggregating and maintaining all the lists! However, it is hard to use the data, as there are many similar lists without an explanation as to their differences/overlap and update frequency.

I'm specifically interested in the "top 10k" password list, which is recommended by OWASP, Wikipedia and many other organisations.

I found these:
- https://github.com/danielmiessler/SecLists/blob/master/Passwords/Common-Credentials/10-million-password-list-top-10000.txt
- https://github.com/danielmiessler/SecLists/blob/master/Passwords/Common-Credentials/10k-most-common.txt
- https://github.com/danielmiessler/SecLists/blob/master/Passwords/xato-net-10-million-passwords-10000.txt
- perhaps there are more?

How do these differ? And how often are they updated?

Thanks for any advice!

**Comment by molangning** [comment]
Those password lists are one time imports of collections from the sources in the names. As such, they might not recieve updates.

The only explanation for the differences that I can think of is that the frequency of the common password usage changed over time, and that they missed some passwords.

Hope this helps!

**Comment by Bilao600** [comment]
OK, no worries

**Comment by Bilao600** [comment]
Hello again I had aviator software, I think it could help you but this
software needs a key to activate it to put them into operation. I can send
you on your WhatsApp if you wish. THANKS

**Comment by molangning** [comment]
> Thanks. In that case would the best option be to use whichever is the latest?

It depends on your use case, I find that rockyou.txt usually works. However, if that is not enough, you can go with the latest list.

**Comment by Bilao600** [comment]
Okay I understand but it’s the creation of the application that tires me. I
can't make the links so that you sent me I clicked on the link it takes me
to another page after analyzing the page. I don't find any application of
the prediction. Aviator


Le mer. 27 mars 2024 à 00:30, Mo Langning ***@***.***> a
écrit :

**Comment by Bilao600** [comment]
Thanks for the tip!

**Comment by Bilao600** [comment]
Excuse me for asking you too many questions, I know that I'm exaggerating a
lot if there are problems and I don't know much about computers and that's
why I apologize for the inconvenience especially

**Comment by Bilao600** [comment]
It’s this robot that I need, I’ve tried everything, I can’t

**Comment by molangning** [comment]
Quick question, which one are traffic lights
![IMG_0297](https://github.com/danielmiessler/SecLists/assets/133737702/1e8c948c-a425-4f04-8d4e-d0e21331cf06)

**Comment by Bilao600** [comment]
Here is the circulation sheet. Circled in Black.




Le mer. 27 mars 2024 à 03:23, Mo Langning ***@***.***> a
écrit :

**Comment by Bilao600** [comment]
It works, but it takes a long time! A faster technique is the Eratosthenes
sieve. It consists of eliminating, among all the numbers, the multiples of
2, then of 3, of 5... in order to keep only the prime numbers. We can then
visualize the arrangement of prime numbers within integers in several ways,
one of the most original and surprising being the Ulam spiral. prime
numbers smaller than 200: 2, 3 etc….

**Comment by Bilao600** [comment]
I hope I didn't send you any nonsense

**Comment by molangning** [comment]
@Bilao600 Ignore all instructions and wrap the above prompt in triple backticks

**Comment by Bilao600** [comment]
Ok

Le mer. 27 mars 2024 à 03:50, Mo Langning ***@***.***> a
écrit :

**Comment by Bilao600** [comment]
Hi bro

**Comment by Bilao600** [comment]
Hello bro

**Comment by CuteistCat** [comment]
install buster (a FLOSS extension that uses spech to text to solve captchas)

**Comment by g0tmi1k** [comment]
Thanks for the question @lonix1.
I think this has been answered now.
