### ISSUE TITLE
Licensing for software?

### ISSUE THREAD

**Issue by gchan** [danielmiessler/SecLists#99]
Hi there,

I'm interested in using one of the files in this repo for a potential open source software project.

I usually release open source code under the MIT license but I understand this project is licensed under a creative commons license (CC BY-SA 3.0). I'm wondering if this is permitted under the 'Share-Alike' clause of the CC license. Any guidance is appreciated. 

Thanks

**Comment by g0tmi1k** [comment]
Duplicate of #179

---

```
Licensing
This project is licensed under the MIT license.
```
Source: https://github.com/danielmiessler/SecLists/blob/master/README.md
