### ISSUE TITLE
[Feature request]: Automated wordlists updater

### ISSUE THREAD

**Issue by molangning** [danielmiessler/SecLists#991]
**Describe the feature request**:
Some wordlists goes stale easily, especially if the update schedule is extremely inconsistent. A github action that checks for updates daily will greatly reduce the time and effort needed to keep a list up to date.

**Next steps**:
It might be possible for changes to be overwritten, so another automation should ideally warn and/or block a pull request that makes changes to a file that will get overwritten next update.

- [x] I intend to open a pull request later

**Comment by Bilao600** [comment]
Ah okay, what is the solution to fall into disuse to be able to resolve
this I think it could come from the updates too


Le mar. 26 mars 2024 à 04:18, Mo Langning ***@***.***> a
écrit :

**Comment by Bilao600** [comment]
This update may take how long according to your opinion

**Comment by molangning** [comment]
Let’s say a few wordlists is imported from other sources which may or may not be from github. The script should check those location and see if there is any remote changes. If there is, the script should pull those and commit those changes. Does that answer your question?

**Comment by Bilao600** [comment]
Afterwards I don't really know if that's the case or not


Le mar. 26 mars 2024 à 05:42, Mo Langning ***@***.***> a
écrit :

**Comment by ItsIgnacioPortal** [comment]
We have already made some Github Actions which periodically check for updates and update the files accordingly: https://github.com/danielmiessler/SecLists/actions

@molangning Is one of the wordlists you're thinking of not covered by those CI flows?

**Comment by molangning** [comment]
@ItsIgnacioPortal There is a great [wordlist](https://raw.githubusercontent.com/wallarm/jwt-secrets/master/jwt.secrets.list) from wallarm that updates irregularly.

There are a lot of wordlists here that are imported from from other sources as well, so I believe that it would be helpful if we can just define a remote source to pull/check daily

**Comment by ItsIgnacioPortal** [comment]
Oh, you mean https://github.com/danielmiessler/SecLists/Passwords/scraped-JWT-secrets.txt. One of the existing github actions could be used as a template for making an updater for this wordlist. If you find any other outdated wordlist, please let me know.

**Comment by molangning** [comment]
Features like crontab can be added
