### ISSUE TITLE
[Bug report]: Dont update

### ISSUE THREAD

**Issue by JackPot777** [danielmiessler/SecLists#993]

**Comment by Bilao600** [comment]
what’s that, big guy, I don’t understand anything in what you sent me


Le mar. 26 mars 2024 à 15:34, JackPot777 ***@***.***> a
écrit :

**Comment by JackPot777** [comment]
What exactly is unclear from the error?

I also don’t understand why it occurs. Occurs only with this repo.

**Comment by Bilao600** [comment]
I can send you my WhatsApp number

‪+33 7 53 09 31 35‬


Le mar. 26 mars 2024 à 15:45, JackPot777 ***@***.***> a
écrit :

**Comment by Bilao600** [comment]
I will send you directly by WhatsApp the software I downloaded

**Comment by JackPot777** [comment]
Thank you, kind human.
Send it to your grandmother via WhatsApp.

**Comment by Bilao600** [comment]
ah I’m really sorry it’s not what you think. Sorry I just wanted to send
you this software don't take it seriously


Le mar. 26 mars 2024 à 15:55, JackPot777 ***@***.***> a
écrit :

**Comment by Bilao600** [comment]
Sorry, I'm really sorry it's not what you think

**Comment by JackPot777** [comment]
Really?
Then send it to your grandfather via WhatsApp.

**Comment by Bilao600** [comment]
Sorry bro pls m’y sorry

Le mar. 26 mars 2024 à 16:11, JackPot777 ***@***.***> a
écrit :
