### ISSUE TITLE
[Question]: Rewrite of generate-environment-identifiers-dict.sh?

### ISSUE THREAD

**Issue by molangning** [danielmiessler/SecLists#998]
The [script](https://github.com/danielmiessler/SecLists/blob/master/.bin/generate-environment-identifiers-dict.sh) uses majestic 1 million.

However, domcorp’s [list](https://www.domcop.com/top-10-million-websites) contains 10 million domains, which would allow us to generate a bigger list.

Additionally, would a python rewrite be appreciated?

@righettod

**Comment by righettod** [comment]
Hi,

Nice idea and proposal 👍 

Feel free to submit a PR with a refactoring of the script 😉

**Comment by molangning** [comment]
Thank you for the feedback! I will do just that.

**Comment by righettod** [comment]
Thank a lot 💯
